Fix Detox Tests
facebook/react-native pull request #30312
Opened 2020-11-03 22:06 UTC by utkarsh-dixit

## Summary

Detox tests were failing because of `DisplayIfVisible` component and `YellowBox`. This PR is meant to fix these issues

## Changelog

[General] [Removed]: Remove DisplayIfVisible component and use simple if else conditions to show which component to show.
[General] [Fixed]: Disable Yellow box so that it doesn't block detox to perform any action on api's test at bottom.

[CATEGORY] [TYPE] - Message

## Test Plan
You can test this PR by,

`yarn build-ios-e2e && yarn test-ios-e2e`

![All Test Passing](https://i.imgur.com/BJg65Qx.png)

2020-11-04 20:45 UTC, hramos commented
Thanks for the fix! Can you re-enable the detox tests on Circle CI as part of this PR? I think you'd only need to uncomment some lines in `.circleci/config.yml`, and then we'll be able to confirm these are fixed.

2020-11-10 07:20 UTC, utkarsh-dixit commented
@hramos I enabled detox tests for iOS in circleci but they are failing because react native fails to build for iOS (mainly for arm64 and i386). I faced the same issue locally when I was building rn-tester for iOS, which I fixed by following the solution in this issue #29984, which was to exclude `arm64` and `i386` architectures when build rn tester app. 


`ld: in /Users/distiller/react-native/packages/rn-tester/Pods/OpenSSL-Universal/ios/lib/libcrypto.a(cryptlib.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/distiller/react-native/packages/rn-tester/Pods/OpenSSL-Universal/ios/lib/libcrypto.a' for architecture arm64`

Do you have any ideas about what is causing this issue?

2020-11-10 16:59 UTC, mkcode commented
There are a few issues here:
 * There is a compilation error of fsevents during the yarn install step
 * We need to `pod update` in order to get the latest Flipper-Folly/OpenSSLUniversal to solve this issue: https://github.com/facebook/react-native/issues/28824
 * We need to disable building for arm64 for now. See: https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios

2020-12-07 08:39 UTC, utkarsh-dixit commented
@hramos Can you review this PR again, the tests are successfully passing on circle CI now

2020-12-08 16:52 UTC, mkcode commented
@utkarsh-dixit - Let's fix the analyze code step first.

2020-12-15 17:30 UTC, mkcode requested changes

2020-12-15 17:30 UTC, mkcode commented on packages/rn-tester/js/RNTesterAppShared.js
> +LogBox.ignoreAllLogs();
Let's test for jest presence here and only disable Logs in detox where jest is defined.

2022-09-22 10:36 UTC, kelset commented
closing this since Detox is not in the repo anymore: https://github.com/facebook/react-native/pull/32907

2022-09-22 10:36 UTC, closed without merging