Update yarn.lock
facebook/react-native pull request #30361
Opened 2020-11-10 19:43 UTC by mkcode

This yarn.lock file was regenerated by deleting the existing yarn.lock file and rerunning `yarn install`.

## Summary

The current `yarn.lock` file is fairly out of date and is affecting the CI servers. 

More specifically, fsevents@1.2.7, [referenced in yarn.lock](https://github.com/facebook/react-native/blob/46be292f671c70aac4ecc178c96e3a2a6a3d16da/yarn.lock#L3215) [fails to compile](https://github.com/fsevents/fsevents/issues/272) on node 12 or later.

This causes the yarn install step on CI to error. See: https://app.circleci.com/pipelines/github/facebook/react-native/7065/workflows/de2bebff-33a5-4d2e-bc73-f7f380641452/jobs/176266/parallel-runs/0/steps/0-104

This PR is being made as 1 step in getting [the RNTester detox tests running again](https://github.com/facebook/react-native/pull/30312).

We can alternatively manually update the `yarn.lock` file with [the minimum needed fsevent changes](https://github.com/facebook/react-native/compare/master...MLH-Fellowship:update-yarn-lock-fsevents?expand=1#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deL3215-L3221) if this PR changes too much.

## Changelog

Will add before merging.

[CATEGORY] [TYPE] - Message

## Test Plan

2020-11-10 19:50 UTC, mkcode commented
Yarn install step on CI looks better with these changes: https://app.circleci.com/pipelines/github/facebook/react-native/7069/workflows/ce93e1d1-64a5-4bfe-9798-d9744dcd8505/jobs/176303/parallel-runs/0/steps/0-104

2020-11-11 02:00 UTC, cpojer requested changes
Can you instead only remove fsevents from yarn.lock and re-run Yarn? We don't want all dependencies to be updated like this.

2020-11-12 01:57 UTC, mkcode commented
@cpojer - Changes made and `yarn install` step on CI looks good. The 1 CI failure is the same as master.

2020-11-12 01:58 UTC, cpojer approved these changes
Nice, that's much better!

2020-11-12 23:30 UTC, closed without merging