[iOS] fix: incorrect ScrollView offset on update
facebook/react-native pull request #30647
Opened 2020-12-26 16:11 UTC by yum650350

## Summary

This pull request is for issue #30258.

After an investigation, I found out the offset of the list seems to be calculated incorrectly due to a workaround in the source code. 

Instead of fixing the `calculateOffsetForContentSize`, I chose to remove it, the reason why I do so is because this workaround is for fixing the offset when `contentSize` is set manually, but according to the source code, there is no interface for a react-native user to override the `contentSize` of ScrollView.

Also I changed the function name from `updateContentOffsetIfNeeded` to  `updateContentSizeIfNeeded` according what the function is actually doing.

## Changelog

[iOS] [Fixed] - Incorrect ScrollView offset on update

## Test Plan

1. Create a fresh new project named `testapp` using npx create-react-native-app
2. Apply example code to `testapp` from https://snack.expo.io/@lokomass/flatlist
3. Run `testapp` on iOS emulator and reproduce the bug
4. Make changes to files in `testapp/node_modules/react-native/`
5. Rebuild `testapp` and run on iOS emulator again, the bug is no more exist
6. Apply changes from step 4 to react-native, make a pull request.

#### Screenshots

Before: The offset is incorrect after children of FlatList has changed

https://user-images.githubusercontent.com/48589760/103155130-b54a0580-47d7-11eb-97af-bdfd3e728714.mov

After: No more incorrect offset if children of FlatList has changed

https://user-images.githubusercontent.com/48589760/103155091-6ef4a680-47d7-11eb-89fa-6f708bfef1c9.mov

2020-12-30 19:20 UTC, shergin commented
Love this PR, I hope this works out!

The `contentSize` property is declared as assignable (`@property (nonatomic, assign) CGSize contentSize;`) but the custom setter is missing. We need to fix this first.

2020-12-30 19:20 UTC, shergin requested changes
See my last comment.

2020-12-31 05:00 UTC, yum650350 commented
> Love this PR, I hope this works out!
> 
> The `contentSize` property is declared as assignable (`@property (nonatomic, assign) CGSize contentSize;`) but the custom setter is missing. We need to fix this first.

Hi @shergin

Let me make it clear, what this PR should do is to fix the `calculateOffsetForContentSize ` instead of removing it, and also there is another issue, the custom setter of `contentSize` is missing and should be fixed.

If I'm not misunderstanding, I should focus on fixing `calculateOffsetForContentSize ` in this PR for issue #30258 , but I'm not sure should fixing "`contentSize` custom setter missing" be part of this PR.

2021-01-02 09:53 UTC, yum650350 commented
@shergin I'm not sure what you mean by fixing the `contentSize` property, I am just removing it as well. Because the `contentContainerStyle` prop is there to let us manually set the content size, seems that `contentSize` property is no longer needed. 

Please let me know if I am on the right or wrong direction of doing this.

2021-01-02 10:57 UTC, yum650350 commented
Have manually checked on react-native `v0.63.4`, it works fine.

Wanted to try on `v0.64.0-rc.2` but facing a build fail issue:
<img width="1298" alt="rn64_build_fail" src="https://user-images.githubusercontent.com/48589760/103455857-b2956600-4d2b-11eb-8272-9f96590e3c57.png">

Cannot check if it works on RN64, I assume that it works as same as `v0.63.4`.

2021-01-05 19:06 UTC, closed without merging

2021-01-08 12:52 UTC, lokomass commented
Amazing thanks !!

2021-05-19 18:36 UTC, lokomass commented
Sorry for this, but I have always this issue with last RN version, is it normal ?

2021-07-08 16:02 UTC, FERARMAO commented
Just add this prop --> automaticallyAdjustContentInsets={false}