add getRecommendedTimeoutMillis to AccessibilityInfo
facebook/react-native pull request #31063
Opened 2021-02-26 16:05 UTC by grgr-dkrk

## Summary
resolve #30866

This PR is for using `getRecommendedTimeoutMillis` with React Native, which is available on Android 10 and above.
This allows the Android "Time to take action (Accessibility timeout)" setting to be reflected in the app.

## Changelog

[Android] [Added] - Add `getRecommendedTimeoutMillis` to AccessibilityInfo

## Test Plan

I couldn't find any tests at the code level, so I tested them on my Android device.

---

### Android 10 (Pixel4a)
#### Settings
<img src="https://user-images.githubusercontent.com/40130327/109322854-210f2400-7896-11eb-9f3b-b88afa27abfb.png" width="400" alt="Set the timeout to 1 minute on the settings screen." />

#### App
<img src="https://user-images.githubusercontent.com/40130327/109322895-32583080-7896-11eb-9c48-c4aa9afb94d9.png" width="400" alt="The baseline timeout is 3000 ms, but the result of `getRecommendedTimeoutMillis` returns 60000 ms." />

---

### Android 7, iOS(Simulator)
Return the original timeout.
<img src="https://user-images.githubusercontent.com/40130327/109323217-911daa00-7896-11eb-9eba-659bc623f2ac.png" width="400" alt="Return the original timeout on Android 7." />

<img src="https://user-images.githubusercontent.com/40130327/109323357-b7dbe080-7896-11eb-89e9-305eea8b801b.png" width="400" alt="Return the original timeout on iOS simulator." />

2021-03-25 12:41 UTC, amarlette commented
Hey, @grgr-dkrk thank you for this PR to help make React Native more accessible! I've added you to our project board. Apologies for this not getting added earlier.

2021-03-29 19:58 UTC, blavalla commented on Libraries/Components/AccessibilityInfo/AccessibilityInfo.android.js
> +    uiContentFlags: AccessibilityUiContentFlagsTypes,
I'm not sure we should bother to surface this param in the javascript API. 

Under the hood it's actually not doing anything, no matter which flag you pass in, the same value comes back. Looking through the Android source, it seems like they originally intended to have two user settings for timings, one for interactive elements, and one for static elements, but at some point this was dropped in favor of a single setting that just sets both values behind the scenes. These flags seem like a vestigial remnant of that original idea, and will likely be removed in a later API version.

@kacieb, does RN generally have a standard for when we should match a platform API strictly versus going with a simpler API if both options have the same end result?

2021-04-02 00:52 UTC, blavalla requested changes

2021-04-02 00:52 UTC, blavalla commented on Libraries/Components/AccessibilityInfo/AccessibilityInfo.android.js
> +    uiContentFlags: AccessibilityUiContentFlagsTypes,
Commenting again to request changes.

2021-04-02 01:02 UTC, blavalla commented
Sorry for the comment churn here, @nadiia is implementing the changes I requested, so no need to any more work @grgr-dkrk! Thanks again for the PR.

2021-04-02 01:02 UTC, blavalla approved these changes

2021-04-06 20:48 UTC, closed without merging

2021-04-06 20:56 UTC, nadiia commented
@grgr-dkrk Thank you for the contribution! Would you be open to add a PR for documenting `getRecommendedTimeoutMillis` in [here](https://github.com/facebook/react-native-website/blob/master/docs/accessibilityinfo.md)?

2021-04-07 00:35 UTC, amarlette commented
Thank you @grgr-dkrk for this contribution! I would like to give you a shout-out on Twitter and include you in our end-of-month issues update for your contribution. Do you have a Twitter we can tag?

2021-04-07 02:24 UTC, grgr-dkrk commented
@blavalla @amarlette @nadiia Thank you for your support!

I have submitted a PR of documentation on this feature.
https://github.com/facebook/react-native-website/pull/2581

My Twitter account is [@]dkrk0901, Thanks.