[Android] Enable isInvertColorsEnabled property to AccessibilityInfo component
facebook/react-native pull request #31070
Opened 2021-02-28 19:49 UTC by MSzalowski

## Summary

This PR enables `isInvertColorsEnabled()` of `AccessibilityInfo` for Android.

That setting is queried using the Settings.Secure.ACCESSIBILITY_DISPLAY_INVERSION_ENABLED property.
https://developer.android.com/reference/android/provider/Settings.Secure#ACCESSIBILITY_DISPLAY_INVERSION_ENABLED

## Changelog

[Android] [Added] -  `isInvertColorsEnabled()` of `AccessibilityInfo`

## Test Plan

Enable and disable color inversion setting in device/emulator accessibility settings and check if property getter updates with a new value.

2021-03-16 20:04 UTC, kacieb commented
Hey! Thanks so much for working on this, this is great! I'm going to tag in @blavalla to check the Android code.

Please also fix the lint related changes when you can, since we'll need those fixed to merge!

2021-03-16 21:46 UTC, blavalla approved these changes
The Android code looks good to me. Just be sure to follow the spacing that the bot suggested to keep things consistent.

2021-03-30 00:27 UTC, blavalla requested changes
Sorry for the delay here, I didn't realize there was a gap here at first!

Let me know if you have any questions for how to implement this.  The approach taken by reduce motion should be exactly what you need to follow here.

2021-03-30 00:27 UTC, blavalla commented on ReactAndroid/src/main/java/com/facebook/react/modules/accessibilityinfo/AccessibilityInfoModule.java
> +  private void updateAndSendInvertColorsChangeEvent() {
Actually, taking another look at this, I think the `updateAndSendInvertColorsChangeEvent()` method isn't being called as often as it should.

You'll want to add a call to this to `onHostResume` (like `updateAndSendReduceMotionChangeEvent()`), and also register a ContentObserver (again like reduce motion) in order to get this to be updated as soon as the setting changes.

2021-05-22 12:42 UTC, MSzalowski commented
Sorry, for the really late update. I don't want to make excuses, but I've had a really busy last few months and haven't had a moment to look here.

@blavalla
I have made the suggested changes. Could you take a look to see if it is ok now?

2021-05-24 19:06 UTC, blavalla requested changes

2021-05-24 19:06 UTC, blavalla commented on ReactAndroid/src/main/java/com/facebook/react/modules/accessibilityinfo/AccessibilityInfoModule.java
> +            AccessibilityInfoModule.this.updateAndSendInvertColorsChangeEvent();
This isn't going to work as part of the same observer.

The way these observers work is that the URI passed into them is a reference to the specific setting changed, and this one is being trigged on `Settings.Global.getUriFor(Settings.Global.TRANSITION_ANIMATION_SCALE);` (line 175 of this file), which is the URI for the animation_scale setting, *not* the display inversion setting.

You'll instead either need to make a second ContentObserver, or use the same observer as you have done, but add a check for the URI in the onChange method and only fire the update method associated with the URI that has triggered it. Whichever approach you opt for you'll also still need to call registerContentObserver with your new URI on line 176 like this:

`mContentResolver.registerContentObserver(Settings.Secure.getUriFor(Settings.Secure.ACCESSIBILITY_DISPLAY_INVERSION_ENABLED), false, YOUR_CONTENT_RESOLVER_HERE);`

Let me know if any of this needs any clarification!

2021-05-24 19:07 UTC, blavalla commented
> Sorry, for the really late update. I don't want to make excuses, but I've had a really busy last few months and haven't had a moment to look here.
> 
> @blavalla
> I have made the suggested changes. Could you take a look to see if it is ok now?

No problem on the timing, whenever you have time to work on this, it's appreciated!

I've commented with one change above.  Let me know if anything needs any clarification!

2021-05-25 07:34 UTC, MSzalowski commented
Everything is clear. Thank you for the detailed information. I'll work on this today

2021-06-01 18:18 UTC, blavalla approved these changes
Thanks for the fixes, this looks great!

2022-12-24 10:13 UTC, XantreGodlike commented
What about this PR. It's seems to be approved but for some reason not merged
@kacieb Can it be approved?
Or there should be some fixes? If so I can help with it)

2022-12-28 07:07 UTC, MSzalowski commented
After years -  I've run google java format on requested files 😅

2022-12-28 07:47 UTC, closed without merging

2022-12-28 07:59 UTC, MSzalowski commented
Due to the conflicts and number of version that were released since I've sent my pr for the first time - I've closed the pr and I'll submit a new one from more recent `main`