Accessibility/button test
facebook/react-native pull request #31189
Opened 2021-03-18 19:48 UTC by huzaifaaak

## Summary
Snapshot test for PR #31001 . This would make sure `accessibilityState` is properly set.

## Changelog

[General] [Added] - Test's for button

## Test Plan

`npm test` to run the test's. 
Since the disabled prop of button has precedence over `accessibilityState.disabled` it would make sure it remains this way.

2021-03-19 16:04 UTC, huzaifaaak commented
@lunaleaps @kacieb Can you please review this

2021-03-31 18:07 UTC, lunaleaps reviewed
Small nit in terms of setting expectations, otherwise looks good!

2021-03-31 18:07 UTC, lunaleaps commented on Libraries/Components/__tests__/Button-test.js
> +  it('should be disabled when disabled={true}', () => {
nit: Should we mention that `accessibilityState` should also be disabled here?

2021-03-31 20:20 UTC, kacieb requested changes
Hey! Thanks so much for writing these tests!

They can be simplified a bit - see my comment on another pull request about the same thing [here](https://github.com/facebook/react-native/pull/31135#issuecomment-805289384).

You can follow the same test structure as [this commit](https://github.com/facebook/react-native/commit/f69e096bb4df67474351786f674b1bb1e42d3363).

2021-04-01 02:23 UTC, lunaleaps commented
@huzaifaaak I'll wait for your response from @kacieb's comment before landing.

2021-04-01 19:14 UTC, huzaifaaak commented
@lunaleaps I have updated the test structure

2021-04-02 18:44 UTC, closed without merging