Do not include Facebook license on users codegen'd code
facebook/react-native pull request #31516
Opened 2021-05-12 16:30 UTC by acoates-ms

## Summary

The codegen generates a Facebook copyright notice at the top of the generated files.  While this might make sense on the core files, this codegen will be run on external components too.   The notice also refers to a LICENSE file in the root of this project, which might not be there if this is run on another project.   I did a quick look at some of the codegen that we ship within windows dev tools, and it looks like we normally just have comments saying the file was codegen'd and so the file shouldn't be manually edited.

Open to suggestions on what the comment header should say.

## Changelog

[General] [Changed] - Do not include Facebook license on users codegen'd code

## Test Plan

2021-05-13 20:09 UTC, hramos commented
Thanks for the PR. Let me run this through our OSS IP team and I'll get back to you.

2021-05-14 21:46 UTC, hramos approved these changes

2021-12-07 10:41 UTC, cortinico requested changes
Hey @acoates-ms,
Thanks for the PR. I'd like to review it and drive it to landing if you wish. 

Can I ask you to:
- Rebase on top of `main`
- Apply the changes I suggested to all the templates?

2021-12-07 10:41 UTC, cortinico commented on packages/react-native-codegen/src/generators/components/GenerateComponentDescriptorH.js
> + * This code was generated by a tool.
```suggestion
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
```

2021-12-07 10:41 UTC, cortinico commented on packages/react-native-codegen/src/generators/components/GenerateComponentDescriptorH.js
> + * the code is regenerated.
```suggestion
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
```

2022-01-06 17:50 UTC, cortinico commented
@acoates-ms I've published this https://github.com/facebook/react-native/pull/32840 that is going to close this PR as it has several merge conflicts + The files inside `src/generators/modules` were missing. So this updates the header for all the generated files 👍

2022-01-19 16:07 UTC, closed without merging