Accessibility/flatlist announcement
facebook/react-native pull request #31630
Opened 2021-05-29 18:06 UTC by anaskhraza

## Summary

Issue #30964 .When using a screen reader, flatlist does not announce entrance/ exit from the flat list.

## Changelog

[Android] [Changed] - Added support for accessibility role of "list" for flatlist and sectioned list

## Test Plan

I have added accessibility role prop in flatlist and sectioned list in rntester app, that will announce entrance/ exit from flatlist and sectioned list.

2021-06-03 22:02 UTC, amarlette commented
Thank you @anaskhraza for this Pull Request! I've gotten you on the Improved React Native Accessibility board and added a reviewer.

2021-06-07 20:09 UTC, blavalla requested changes

2021-06-07 20:09 UTC, blavalla commented on ReactAndroid/src/main/java/com/facebook/react/uimanager/ReactAccessibilityDelegate.java
> +          return "android.widget.ListView";
You'll want to make this "android.widget.AbsListView.class" to match Talkback's internal implementation here:

https://github.com/google/talkback/blob/f5d564fdc915a74d8cde4868608f307de9ccf957/utils/src/main/java/com/google/android/accessibility/utils/Role.java#L380

2021-06-21 19:09 UTC, blavalla approved these changes
Looks good, thanks for the fix!

2021-07-10 02:25 UTC, closed without merging