Foreground ripple support in Pressable
facebook/react-native pull request #31632
Opened 2021-05-30 16:09 UTC by intergalacticspacehighway

## Summary
This PR aims to enable support for foreground ripple in Pressable. This makes it possible to show ripple on top of custom child components like Image as shown in the below example.

## Changelog

[Android] [Added] - Support for foreground ripple in Pressable

## Test Plan

- Pass property useForeground: true in android_ripple config to verify the changes.

https://user-images.githubusercontent.com/23293248/120111371-4cecbf00-c18f-11eb-8acb-d10718d5483c.mov

2021-06-03 00:45 UTC, TheSavior commented
Looks like the JavaScript tests are failing due to a missing dep in the useMemo array.

2021-06-06 23:40 UTC, yungsters requested changes
Provided some minor feedback.

2021-06-06 23:40 UTC, yungsters commented on Libraries/Components/Pressable/Pressable.js
> +  let restPropsWithDefaults: React.ElementConfig<typeof View> = {
Can you keep this as `const` and instead create a new `const` local variable that contains the ripple props (or remains undefined) that you spread in here?

It's a minor code reorganization, but it helps keep the code slightly more readable in the long-term the more you can have `const` variables that — as you read the declaration — you know will not be reassigned later.

2021-06-06 23:40 UTC, yungsters commented on Libraries/Components/Pressable/useAndroidRippleForView.js
> +  useForeground?: boolean,
Can you just name this `foreground`? Even though it is a property name and not a variable name, avoiding the "use" prefix is just better in the current world with hooks.

2021-06-06 23:40 UTC, yungsters commented on Libraries/Components/Pressable/useAndroidRippleForView.js
> +      let viewProps = {};
Similar feedback as above about making this `const`. You can also instantiating this after `backgroundValue`:

```
const viewProps = foreground === true
  ? {nativeForegroundAndroid: backgroundValue}
  : {nativeBackgroundAndroid: backgroundValue};
```

Could even return this to line 80 as a ternary property initialization in the return statement.

2021-06-06 23:40 UTC, yungsters commented on Libraries/Components/Pressable/useAndroidRippleForView.js
> +  }, [color, borderless, radius, viewRef, useForeground]);
Nit: Alphabetize (after renaming to `foreground`).

2021-06-08 00:08 UTC, closed without merging