refactor: remove DefaultProps from the StatusBar Component
facebook/react-native pull request #31631
Opened 2021-05-29 22:07 UTC by Fannolo

## Summary

Issue #31607. defaultProps makes it difficult to migrate components to functional.

## Changelog

[General] [Changed] -  Remove defaultProps from the StatusBar Component.

## Test Plan

Verified the behaviour of the existing functionality after the removal on the RN Tester app.

https://user-images.githubusercontent.com/11355609/120085709-a2b35f80-c0da-11eb-94f2-2649270155ef.mov

2021-05-31 16:25 UTC, lunaleaps requested changes
We want to remove `defaultProps` from the component but still want the default value to be applied. Right now, whenever you use `props.animated` or `props.showHideTransition`, the value will be undefined if a user does not supply the prop. We need to make sure all access of these props still have a default value -- we just don't want to use React's defaultProps construct to ensure that. 

Please add a snapshot test as well to verify these props. You can take a look at how VirtualizedList does Jest snapshots. 
Let me know if that makes sense!

2021-06-04 17:16 UTC, Fannolo commented
Hi @lunaleaps! Thank you for your suggestion! I just made a new commit could you take a look at it and see if that's what you had in mind? I added default value to the animated prop and showHideTransition prop whenever createStackEntry is called, so when you have animated or showHideTransition set to undefined, the values will be automatically set to false and "fade" respectively.

2021-06-05 02:19 UTC, lunaleaps commented
@Fannolo Great thank you! Would you also be interested in writing a jest test for this component? You can take a look at VirtualizedList-test as an example: https://github.com/facebook/react-native/blob/dc80b2dcb52fadec6a573a9dd1824393f8c29fdc/Libraries/Lists/__tests__/VirtualizedList-test.js

you can check out the Jest API: 
and run the the test via

yarn test <name of your test>

2021-06-13 15:58 UTC, Fannolo commented
> @Fannolo Great thank you! Would you also be interested in writing a jest test for this component? You can take a look at VirtualizedList-test as an example: https://github.com/facebook/react-native/blob/dc80b2dcb52fadec6a573a9dd1824393f8c29fdc/Libraries/Lists/__tests__/VirtualizedList-test.js
> 
> you can check out the Jest API:
> and run the the test via
> 
> yarn test [name of your test]

Hi @lunaleaps, I added some tests to the StaturBar component could you take a look and see if I'm going on the right direction? Thanks!

2021-06-16 08:03 UTC, lunaleaps commented
@Fannolo Yup! That looks great! Great to assert that the value of the prop is set to its default if not passed in. You can also try running your tests before and after your changes to see if anything has changed.

2021-07-27 07:29 UTC, Fannolo commented
Hi @lunaleaps sorry for the long wait, I checked if the tests were working with the old version of the code and everything looks fine! Lemme know if you can review the pull request!

2021-08-18 08:23 UTC, closed without merging