Enable Generic Discontiguous Regions within VirtualizedList
facebook/react-native pull request #32638
Opened 2021-11-21 22:53 UTC by NickGerleman

## Summary

This builds upon the `CellRenderMask` data structure added with https://github.com/facebook/react-native/pull/31420, and VirtualizedList coverage added with https://github.com/facebook/react-native/pull/31401, to allow more discontiguous structures in VirtualizedList. This enables keyboard/a11y scenarios, where focus may be outside of a viewport-derived region.

VirtualizedList currently keeps a [first, last] range as state, tracking the region of cells to render. The render functions uses this as an input, along with a few special cases to render more (sticky headers, initial render region.)

This change moves to instead keep state which describes discontiguous render regions. This mask is continually updated as the viewport changes, batch renders expand the region, etc. Special cases are baked into the render mask, with a relatively simple transformation from the mask to render function.

MS/FB folks have a video discussion about VirtualizedList here: https://msit.microsoftstream.com/video/fe01a1ff-0400-94b1-d4f1-f1eb924b1809

## Changelog

[Internal] [Added ] - Discontiguous VirtualizedList Regons

## Test Plan

facebook/react-native#31401 added quite a few snapshot tests, centering around the logic this change is touching. I manually validated RNTester FlatList examples (and their should be some upstream UI testing for them).

2021-11-21 22:55 UTC, NickGerleman commented on Libraries/Lists/__tests__/__snapshots__/VirtualizedList-test.js.snap
> -    <View
There are some cases like this, where we render less, but the new behavior looks more correct to me given inputs.

2021-11-21 23:19 UTC, NickGerleman commented
FYI to reviewers, there is quite a bit of code where chunks of logic have moved. I've tried to keep most of the existing blocks where possible, but you might need to hop around a bit to see where some of the chunks came from.

2021-12-01 02:19 UTC, lunaleaps requested changes
Is it possible to split up this diff into just changing the state representation of the existing contiguous region and then the changes in supporting discontiguous? 

Or perhaps even more granular if possible in other aspects in the case that something ends up breaking some of our products, it might be clearer which parts are problematic or reveals problematic assumptions. And additionally if we could use a feature flag

2021-12-01 03:04 UTC, NickGerleman commented
I didn't see a straightforward way to split this much further. The discontiguous regions added to the mask are present before, but special cased into the render function.

I agree we should gate this though. Way long ago, @TheSavior recomended keeping the changes inline for review, then cloning to a second component that can be injected before merging. That would allow FB folks to flight the change (the infrastructure is not in OSS). 

We're separately doing a gated rollout of this to Office right now.

2021-12-01 04:01 UTC, NickGerleman commented
I can also let this change rest until we get feedback from a production-level audience internally.

2022-06-24 02:16 UTC, closed without merging