fix: Removes interface only check from third party components GenerateThirdPartyFabricComponentsProvider
facebook/react-native pull request #32779
Opened 2021-12-17 10:12 UTC by Ubax

## Summary

Currently the codegen does not include component with field `interfaceOnly` set to `true` in the `ThirdPartyFabricComponentsProvider`. 

These components need to be added to this file, so that non-core components can be used in fabric.

## Changelog

[General [Fixed] - Fixes GenerateThirdPartyFabricComponentsProvider

## Test Plan

Run codegen with component outside of core on iOS. 

Check if components with and without `interfaceOnly` are added to `RCTThirdPartyFabricComponentsProvider`

2021-12-17 14:05 UTC, sota000 commented
Thanks, @Ubax! cc: @sammy-SC

2021-12-17 14:06 UTC, sota000 commented
Ohh, I need the CLA to be added. I'll import it after that's added. cc: @Ubax

2021-12-17 14:20 UTC, sota000 requested changes
Just to get this back on your plate about the CLA.

2021-12-20 10:49 UTC, Ubax commented
@sota000  I filled CLA

2021-12-20 14:33 UTC, ShikaSD commented
hey, do you mind also updating test fixtures in the `packages/react-native-codegen/src/generators/components/__tests__/` folder? Seems like updated generator (expectedly) generates a bit more things there :)

2021-12-20 14:38 UTC, Ubax commented
Yeah sure

2021-12-20 14:51 UTC, Ubax commented
@ShikaSD done

2021-12-20 19:29 UTC, janicduplessis commented
Awesome, I hit this issue too when trying the new architecture with an interfaceOnly component. I can confirm this fixes the issue.

2021-12-20 19:45 UTC, closed without merging