Fix items disappear when zooming VirtualizedList
facebook/react-native pull request #33765
Opened 2022-05-05 05:46 UTC by islandryu

## Summary

fix #33705
Fixed the disappearance of items when scrolling after zooming VirtualizedList.

Before modification

https://user-images.githubusercontent.com/65934663/166849127-9fc3ba84-5172-4ae1-bd44-dd6312f283ec.mov

After modification

https://user-images.githubusercontent.com/65934663/166868632-2f78e118-f705-442d-b94e-ff165bed26c7.mov

## Changelog

[General] [Fixed] - Fixed the disappearance of items when scrolling after zooming VirtualizedList.

## Test Plan
Make the VirtualizedList zoomable with a prop such as maximumZoomScale.
Apply the patch and make sure that items in the VirtualizedList do not disappear when you scroll after zooming the VirtualizedList.

Or apply the patch from this repository and check it.
https://github.com/islandryu/zoomVirtualizedList

2022-05-05 16:24 UTC, yungsters reviewed
Awesome, thanks for this improvement.

2022-05-05 22:00 UTC, yungsters requested changes
The `VirtualizedList-test.js` Jest test seems to be failing after this change. Specifically, the "keeps sticky headers above viewport visualized" test is failing. Can you take a look?

2022-05-06 07:58 UTC, islandryu commented on Libraries/Lists/VirtualizeUtils.js
> +  zoomScale: number,
Fixed so that the test passes.

2022-05-06 07:59 UTC, islandryu commented on Libraries/Lists/VirtualizedListContext.js
> +    ...
Fixed.

2022-05-06 16:33 UTC, closed without merging