Change Wrapper of InspectorPanel from View to SafeAreaView
facebook/react-native pull request #34500
Opened 2022-08-25 18:22 UTC by raykle

## Summary

Currently, the `InspectorPanel` component is wrapped in `View`, which is a little difficult to click the panel button when in a device with a notch screen.

## Changelog

[General] [Fixed] - Change Wrapper of `InspectorPanel` from `View` to `SafeAreaView`

## Test Plan

**From:**

<img alt="" height="500" src="https://user-images.githubusercontent.com/3097366/186088404-32cb2707-a4f1-45d6-9f83-f0992d5ba64d.png"> <img alt="" height="500" src="https://user-images.githubusercontent.com/3097366/186088438-863fd7da-b827-4cc1-b873-f0bf38764e83.png">

**To:**

<img alt="" height="500" src="https://user-images.githubusercontent.com/3097366/186088518-6e131a8e-27ae-4eed-b97d-ee6f6ab5e669.png"> <img alt="" height="500" src="https://user-images.githubusercontent.com/3097366/186088550-35ce0512-ac4f-4ef1-b5db-f2a3ec434b24.png"> <img alt="" height="500" src="https://user-images.githubusercontent.com/3097366/186088579-ff42ee60-6b1c-4179-aae8-764f4d04e680.png">

2022-08-26 13:15 UTC, cipolleschi commented
Hi @raykle, could you please rebase your PR?

2022-08-29 17:15 UTC, lunaleaps requested changes
Hmm I think there are a lot of changes here unrelated to your PR, either from the rebase or potentially different lints. Can you  clean this up to only your changes? Thanks!

2022-08-30 02:53 UTC, raykle commented
Hi @lunaleaps, I have rebase the PR.

2022-08-30 15:58 UTC, lunaleaps commented on Libraries/Inspector/InspectorPanel.js
> +const SafeAreaView = require('../Components/SafeAreaView/SafeAreaView').default;
```suggestion
import SafeAreaView from '../Components/SafeAreaView/SafeAreaView';
```

2022-08-30 18:42 UTC, lunaleaps requested changes
Sorry, was my suggestion wrong? I think we can use es6 imports here no?

2022-08-31 02:11 UTC, raykle commented
Hi @lunaleaps , Sorry about that, I'm a little not familiar with the `GitHub Pull Request flow`, and I clicked the `resolve conversation` by mistake.

I agree with your suggestion absolutely! 
What should I do now? Change the code and push again?

2022-08-31 02:24 UTC, raykle commented
modified the code and also rebased it.

2022-08-31 16:31 UTC, lunaleaps approved these changes

2022-08-31 16:31 UTC, lunaleaps commented
Great, thank you!

2022-08-31 18:47 UTC, closed without merging