feat: add aria-disabled aliasing for button
facebook/react-native pull request #34521
Opened 2022-08-28 14:00 UTC by ankit-tailor

## Summary

This adds the `aria-disabled` prop to the `Button` component where it's used as requested on https://github.com/facebook/react-native/issues/34424, mapping web [aria-disabled](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-disabled) to equivalent [accessibilityState](https://reactnative.dev/docs/accessibility#accessibilitystate)

## Changelog

Add `aria-disabled` prop to `Button` component

[CATEGORY] [TYPE] - Message

## Test Plan

```
<Button
  aria-disabled={true}
  onPress={() => onButtonPress('submitted')}
  testID="accessibilityState_button"
  color={theme.LinkColor}
  title="Submit Application"
  accessibilityLabel="Press to submit your application!"
/>
```

2022-08-28 18:22 UTC, necolas requested changes
This is limited only to `Button` (which is a component we intend to deprecate anyway), rather than generally being an alias for `accessibilityState.disabled`

2022-08-29 06:01 UTC, ankit-tailor commented
Hi @necolas, I'll add it for core components. I just wanted to know if this is the correct way.

2022-08-29 06:32 UTC, necolas commented
Looks reasonable to me given how accessibilityState was working

2022-08-29 06:48 UTC, ankit-tailor commented
Then I'll create another PR having all accessibility states aliasing for core components.

2022-08-29 08:04 UTC, closed without merging