feat: added accessibility value aliases
facebook/react-native pull request #34535
Opened 2022-08-30 15:10 UTC by dakshbhardwaj

## Summary
This adds aliasing for accessibility Value, it's used as requested on https://github.com/facebook/react-native/issues/34424.

- [aria-valuemax](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-valuemax) to equivalent [accessibilityValue.max](https://reactnative.dev/docs/accessibility#accessibilityvalue)
- [aria-valuemin](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-valuemin) to equivalent [accessibilityValue.min](https://reactnative.dev/docs/accessibility#accessibilityvalue)
- [aria-valuenow](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-valuenow) to equivalent [accessibilityValue.now](https://reactnative.dev/docs/accessibility#accessibilityvalue)
- [aria-valuetext](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-valuetext) to equivalent [accessibilityValue.text](https://reactnative.dev/docs/accessibility#accessibilityvalue)

## Changelog

[General] [Added] - Add `aria-valuemax`, `aria-valuemin`, `aria-valuenow`, `aria-valuetext` as alias prop to `TouchableOpacity`, `View`, `Pressable` `TouchableHighlight` `TouchableBounce` `TouchableWithoutFeedback` `TouchableOpacity` components

## Test Plan
 - Enable `talkback`.
 - Open the RNTester app and navigate to the Api's tab
 - Go to the `fake Slider Example for Accessibility Value `modes section
 
<Image src="https://user-images.githubusercontent.com/22423684/187472543-05200d8d-2742-4096-a56c-41f81b440a97.png" height="600" width="300" />

2022-08-30 16:48 UTC, jacdebug commented
Thanks for working on this, could you please have a look on failing test.

2022-09-08 10:24 UTC, jacdebug requested changes
Sorry for late review, please see inline comment for changes requested.

2022-09-08 10:24 UTC, jacdebug commented on Libraries/Components/Pressable/Pressable.js
> +        : props.accessibilityValue?.max,
```suggestion
        : props.accessibilityValue?.text,
```

2022-09-08 10:24 UTC, jacdebug commented on Libraries/Components/Touchable/TouchableBounce.js
> +          : this.props.accessibilityValue?.max,
```suggestion
          : this.props.accessibilityValue?.text,
```

2022-09-08 10:24 UTC, jacdebug commented on Libraries/Components/Touchable/TouchableHighlight.js
> +          : this.props.accessibilityValue?.max,
```suggestion
          : this.props.accessibilityValue?.text,
```

2022-09-08 10:24 UTC, jacdebug commented on Libraries/Components/Touchable/TouchableNativeFeedback.js
> +          : this.props.accessibilityValue?.max,
```suggestion
          : this.props.accessibilityValue?.text,
```

2022-09-08 10:24 UTC, jacdebug commented on Libraries/Components/Touchable/TouchableOpacity.js
> +          : this.props.accessibilityValue?.max,
```suggestion
          : this.props.accessibilityValue?.text,
```

2022-09-08 10:24 UTC, jacdebug commented on packages/rn-tester/js/examples/Accessibility/AccessibilityExample.js
> +          aria-valuenow={this.state.current}>
Could you please add test for `aria-valuetext` as well

2022-09-08 16:04 UTC, jacdebug requested changes
One more left

2022-09-08 16:04 UTC, jacdebug commented on Libraries/Components/Pressable/Pressable.js
> +        : props.accessibilityValue?.max,
```suggestion
        : props.accessibilityValue?.text,
```

2022-09-08 16:30 UTC, dakshbhardwaj commented
> One more left

@jacdebug pushed the changes

2022-09-08 17:18 UTC, jacdebug commented
there are some new conflicts @dakshbhardwaj

2022-09-08 17:31 UTC, dakshbhardwaj commented
> there are some new conflicts @dakshbhardwaj

@jacdebug I have resolved the conflicts

2022-09-09 07:53 UTC, jacdebug requested changes
Please see inline commend use nullish coalescing operator is correct and make code more readable.

2022-09-09 07:53 UTC, jacdebug commented on Libraries/Components/Pressable/Pressable.js
> +        : props.accessibilityValue?.max,
```suggestion
    max: props['aria-valuemax'] ?? props.accessibilityValue?.max,
```

This is more accurate and simple, please update the change for rest of properties on all changed files.

2022-09-09 08:35 UTC, dakshbhardwaj commented
> Please see inline commend use nullish coalescing operator is correct and make code more readable.

@jacdebug I have made the changes

2022-09-09 10:25 UTC, jacdebug approved these changes

2022-09-09 11:51 UTC, closed without merging