[Codegen] Extract RootTag case of translateTypeAnnotation from the flow and typescript folders in parsers-primitives
facebook/react-native pull request #34901
Opened 2022-10-08 14:38 UTC by MaeIg

## Summary

This PR aims to reduce code duplication by extracting `emitRootTag` logic from the flow and typescript folders into a shared parsers-primitives file. It is a task of #34872:
> Extract the content of the case 'RootTag' (Flow TypeScript) into a single emitRootTag function in the parsers-primitives.js file. Use the new function in the parsers.

Note that #34898 should be merged first. I rebased on it's branch.

## Changelog

[Internal] [Changed] - Extract RootTag case of translateTypeAnnotation from the flow and typescript folders in parsers-primitives

## Test Plan

All tests are passing, with `yarn jest react-native-codegen`:
<img width="934" alt="image" src="https://user-images.githubusercontent.com/40902940/194696891-6921e050-fb69-48c6-b55d-944f907fb7e3.png">

2022-10-09 13:26 UTC, cipolleschi requested changes
Thanks for taking this. 👏 That's amazing!

We can improve the quality even further byadding a unit test.
The steps should be:
1. add the `__tests__` subfolder in the `packages/react-native-codegen/src/parsers`.
2. add a `parser-primitives-test.js` where we unit test this fuction:
    1. we test the output when the `nullable` parameter is `false`
    1. we test the output when the `nullable` parameter is `true`

An example of unit test can be [found here](https://github.com/facebook/react-native/blob/main/packages/react-native-codegen/src/cli/combine/__tests__/combine-utils-test.js#L16-L37). 

Thank you so much! :pray:

2022-10-09 20:00 UTC, MaeIg commented
> Thanks for taking this. 👏 That's amazing!
> 
> We can improve the quality even further byadding a unit test. The steps should be:
> 
> 1. add the `__tests__` subfolder in the `packages/react-native-codegen/src/parsers`.
> 2. add a `parser-primitives-test.js` where we unit test this fuction:
>    
>    1. we test the output when the `nullable` parameter is `false`
>    2. we test the output when the `nullable` parameter is `true`
> 
> An example of unit test can be [found here](https://github.com/facebook/react-native/blob/main/packages/react-native-codegen/src/cli/combine/__tests__/combine-utils-test.js#L16-L37).
> 
> Thank you so much! 🙏

Thanks for the review!

I thought this case was already covered in these files ([flow](https://github.com/facebook/react-native/blob/main/packages/react-native-codegen/src/parsers/flow/modules/__tests__/module-parser-e2e-test.js) and [typescript](https://github.com/facebook/react-native/blob/main/packages/react-native-codegen/src/parsers/typescript/modules/__tests__/typescript-module-parser-e2e-test.js)). But you're right, it's clearer and safer to test `emitRootTag` function 😁

It's done if you want to re-review it!

2022-10-09 22:43 UTC, rshest commented
@MaeIg Just a heads up - looks like there are some conflicting changes  in the new main, have to be resolved before merging.

2022-10-09 22:57 UTC, MaeIg commented
> @MaeIg Just a heads up - looks like there are some conflicting changes in the new main, have to be resolved before merging.

@rshest  I rebased. Thanks 🙂

2022-10-10 10:51 UTC, cipolleschi approved these changes

2022-10-10 11:29 UTC, closed without merging