Extract MisnamedModuleInterfaceParserError from Flow and Typescript into error-utils.js
facebook/react-native pull request #34916
Opened 2022-10-10 06:53 UTC by mohitcharkha

## Summary

This PR is part of #34872 
This PR extracts MisnamedModuleInterfaceParserError from Flow and Typescript into error-utils.js

## Changelog

[Internal] [Changed] - Extracted MisnamedModuleInterfaceParserError from Flow and Typescript into error-utils.js

## Test Plan

yarn jest react-native-codegen

<img width="980" alt="Extract MisnamedModuleInterfaceParserError test Screenshot" src="https://user-images.githubusercontent.com/86604753/194811658-a2421331-8e03-4568-9616-55c229f52749.png">

2022-10-10 08:07 UTC, AntoineDoubovetzky commented
@mohitcharkha I don't think the goal of this task was to extract the error itself, it is done for all errors here: https://github.com/facebook/react-native/pull/34896

The goal is to extract the logic that makes the check and throw if necessary (see https://github.com/facebook/react-native/issues/34872#issuecomment-1272930315)

2022-10-10 08:15 UTC, cipolleschi commented on packages/react-native-codegen/src/parsers/flow/modules/index.js
>      );
The tasks was slightly different: this PR export just the type from the `index.js` to the `error-utils`.
However, this step was responsibility of #34896 (which this PR should depend on).

What I was expecting here, was a function like:
```
function throwIfModuleInterfaceIsMisnamed(nativeModuleName: string, module: ASTNode, parserType: ParserType) {
  if (moduleSpec.id.name !== 'Spec') {
    throw new error
  }
}
```

That will replace these 6 lines in the `flow/modules/index.js` and in the `typescript/modules/index.js`.

In this way:
1. if we need to update the logic that throws the error, we do it in a single place
2. the parser code is more readable and self documenting.

Could you update this with this suggestion?

Thank you so much! 🙏

2022-10-10 08:16 UTC, cipolleschi commented on packages/react-native-codegen/src/parsers/typescript/modules/index.js
>    }
Same change described above! 😉

2022-10-10 08:16 UTC, cipolleschi commented on packages/react-native-codegen/src/parsers/error-utils.js
> +type ParserTypes = 'Flow' | 'TypeScript';
I love this! 😄  I'm moving the suggestion to the other PR (#34896).

2022-10-10 09:03 UTC, cipolleschi commented
Also, given that we are introducing a new function, it would be great to have a unit test for it!

2022-10-10 11:16 UTC, cipolleschi approved these changes
Looks good! Thank you so much for taking this task!

2022-10-10 13:47 UTC, cipolleschi requested changes

2022-10-10 13:47 UTC, cipolleschi commented on packages/react-native-codegen/src/parsers/__tests__/error-utils-test.js
> + * @oncall react_native
Could you please enable flow in the test file? You can do it by adding this line in the license:

```suggestion
 * @flow strict-local
 * @oncall react_native
```

2022-10-14 15:24 UTC, cipolleschi commented
@mohitcharkha could you rebase and resolve the conflicts, please?

2022-10-17 06:27 UTC, mohitcharkha commented on packages/react-native-codegen/src/parsers/typescript/modules/index.js
> +  throwIfMoreThanOneModuleRegistryCalls,
```suggestion
```

2022-10-17 06:28 UTC, mohitcharkha commented on packages/react-native-codegen/src/parsers/flow/modules/index.js
> +  throwIfMoreThanOneModuleRegistryCalls,
```suggestion
```

2022-10-17 07:26 UTC, cipolleschi commented
/rebase

2022-10-17 11:50 UTC, cipolleschi approved these changes

2022-10-17 13:50 UTC, closed without merging