chore: Add getKeyName function to codegen Parser class
facebook/react-native pull request #35202
Opened 2022-11-04 16:41 UTC by gabrieldonadel

## Summary

This PR adds a  `getKeyName`  function to the codegen Parser class and implements it in the Flow and TypeScript parsers as requested on https://github.com/facebook/react-native/issues/34872. 

## Changelog
 

[Internal] [Added] - Add `getKeyName` function to codegen Parser class

## Test Plan

Run `yarn jest react-native-codegen` and ensure CI is green

![image](https://user-images.githubusercontent.com/11707729/200028600-87e9c1d7-d56d-4cf7-bdbc-18bdf1b03fc5.png)

2022-11-07 17:08 UTC, cipolleschi requested changes
Amazing work, thank you for doing this! 👏 

What do you think about adding a unit test for the TypeScript parser and for the Flow parser?

Now that we have some small nice functions in the Parsers, it would be nice to test them!

2022-11-08 01:44 UTC, gabrieldonadel commented
> What do you think about adding a unit test for the TypeScript parser and for the Flow parser?

Sure, that sounds like a great idea, I've just pushed a commit adding some unit tests for both Parsers.

2022-11-10 13:43 UTC, gabrieldonadel commented
Hi @cipolleschi everything should've been updated now, do you mind taking another look?

2022-11-10 15:00 UTC, cipolleschi approved these changes

2022-11-10 17:07 UTC, closed without merging