Add intersection types in react-native-codegen for TypeScript
facebook/react-native pull request #35247
Opened 2022-11-07 20:29 UTC by ZihanChen-MSFT

## Summary

Refer to "Support intersection of object types, `{...a, ...b, ...}` in Flow is equivalent to `a & b & {...}` in TypeScript, the order and the form is not important." in https://github.com/facebook/react-native/issues/34872

In this change I also extract the common part from `getTypeAnnotation` and `getTypeAnnotationForArray` into `getCommonTypeAnnotation`. Most of the differences are about `default` in the schema. After a schema is generated from `getCommonTypeAnnotation` successfully, `getTypeAnnotation` will fill `default` if necessary, while `getTypeAnnotationForArray` does nothing.

## Changelog

[General] [Changed] - Add intersection types in react-native-codegen for TypeScript

## Test Plan

`yarn jest react-native-codegen` passed

2022-11-08 09:07 UTC, cipolleschi requested changes
Thanks for doing this, it will help many people with the New aArchitecture writing better specs! I left two comments to improve the readability of the code.

2022-11-08 21:42 UTC, ZihanChen-MSFT commented on packages/react-native-codegen/src/parsers/typescript/components/componentsUtils.js
> +
Fixed

2022-11-08 21:46 UTC, ZihanChen-MSFT commented on packages/react-native-codegen/src/parsers/typescript/components/componentsUtils.js
> +    return common;
Fixed

2022-11-10 14:45 UTC, cipolleschi approved these changes

2022-11-10 23:35 UTC, closed without merging