Nested horizontal virtualized list viewability
facebook/react-native pull request #35248
Opened 2022-11-07 23:18 UTC by vincentvella

## Summary
See #35180 

## Changelog

[CATEGORY] [TYPE] - Message

## Test Plan

Working on adding some jest tests but there's some interesting stuff happening with react-test-renderer in the flatlist. Doesn't seem easy to test at this point.
https://user-images.githubusercontent.com/22749569/200435788-31abe231-3fc5-498d-979e-aa4f3f12798b.mp4

2022-11-08 00:28 UTC, NickGerleman requested changes
Thanks for the contribution!

The approach of keeping track of whether the outer cell is visible isn't quite correct I think, since the inner list can still be arbitrarily offset within the cell to not be visible itself. I have a PR internally where we nested lists are fully aware of their cross-axis position to account for this. It ended up adding complexity and I thought it may be worth pulling out the viewability logic to a unique component, but it seems like folks are repeatedly hitting this so it might be worth cleaning up again and submitting.

2022-11-08 01:27 UTC, vincentvella commented
> since the inner list can still be arbitrarily offset within the cell to not be visible itself.

@NickGerleman is there any chance you have an example of what you're describing above? It'll be useful to help diagnose the issues with this PR. For my particular use-case this solves the issue I'm attempting to get past so I might use this as a temporary patch until your version/strategy is merged.

My thought process was if an inner cell was no longer visible or became not visible at a time post-render it'd fire one of the layout events and the list would recalculate its positioning but I'm interested to see if there's an edge case I'd missed

2022-11-08 01:27 UTC, vincentvella commented
> since the inner list can still be arbitrarily offset within the cell to not be visible itself.

@NickGerleman is there any chance you have an example of what you're describing above? It'll be useful to help diagnose the issues with this PR. For my particular use-case this solves the issue I'm attempting to get past so I might use this as a temporary patch until your version/strategy is merged.

My thought process was if an inner cell was no longer visible or became not visible at a time post-render it'd fire one of the layout events and the list would recalculate its positioning but I'm interested to see if there's an edge case I'd missed

2022-11-12 14:36 UTC, NickGerleman commented
In the below example, cell 2 is visible, but none of the children in the nested list are yet visible in the horizontal axis. So deriving visibility from whether the list is in a visible cell doesn't work quite generically.

A solution you can use to do that accurately is to instead thread both main-axis and cross-axis position down the child contexts. That allows individual lists to know their viewport coverage in both axis. It means requirements like "must be 20% visible" can also apply to the cross-axis as well.

Last week has been hectic, but I can export the change as a GitHub PR and retest it soon. Part of why I was holding off is that this change will need more UTs than what I had added, or the nested RNTester example you discovered. 

<img width="638" alt="image" src="https://user-images.githubusercontent.com/835219/201478325-7443eb97-7b6c-4e5b-bf4c-1a225d3a78d4.png">

2022-11-15 19:24 UTC, vincentvella commented
> 

This makes total sense, I'm happy to help with any unit testing if you are able to export the PR to Github!
I attempted to do something similar but I was attempting to reach up from the child to get the scroll positioning. I think it may have only been grabbing the outermost parent because it wasn't firing the onViewableItemsChanged appropriately anymore.

2023-03-20 17:07 UTC, closed without merging