make `react_native_path` path agnostic
facebook/react-native pull request #35687
Opened 2022-12-20 12:21 UTC by dcangulo

## Summary

On the usual flow, we use `cd ios; bundle exec pod install;` to install pods which makes the path `"../node_modules/react-native"` correct.

But pods support `--project-directory` which in my case I use `bundle exec pod install --project-directory=ios` from the root directory instead of navigating into `ios` folder.

This raises the following error:
```
No such file or directory @ rb_sysopen - ../node_modules/react-native/package.json

/Users/davidangulo/Desktop/mobile/myapp/node_modules/react-native/scripts/react_native_pods.rb:212:in `read'
/Users/davidangulo/Desktop/mobile/myapp/node_modules/react-native/scripts/react_native_pods.rb:212:in `react_native_post_install'
```

This PR makes it path agnostic so that it works with both.

## Changelog

[IOS] [CHANGED] - make `react_native_path` path agnostic

## Test Plan

Should build as is.

2022-12-20 13:40 UTC, cipolleschi requested changes
Hi @dcangulo, thank you for the PR.

However, as you can see from the signature, the parameter is there so that you can customize it in your specific setup. In your case, you can update your `Podfile` by calling the post install method as

```ruby
react_native_post_install(installer, File.expand_path("..", __dir__))
```

We added a configurable parameter exactly for these use cases. I'm a bit concern about changing the default parameter: we can't support all the possible setups.
The template works with `../node_modules/react-native`. But, RNTester doesn't for example, and we [customize it](https://github.com/facebook/react-native/blob/main/packages/rn-tester/Podfile#L72). You may have found a way to make this work with your setup and the template... but what about users with some different setups/monorepos? They may have other requirements as well. 

We can't support them all by default. So, the proper approach would be to update the project you are working on to pass the right path.

2022-12-20 14:32 UTC, dcangulo commented
> However, as you can see from the signature, the parameter is there so that you can customize it in your specific setup. In your case, you can update your `Podfile` by calling the post install method as
> 
> ```ruby
> react_native_post_install(installer, File.expand_path("..", __dir__))
> ```

This seems incorrect. `__dir__` is the current directory of the file, while `File.expand_path("..", __dir__)` is the parent directory of the current directory.

Calling `File.expand_path("..", __dir__)` on `/Users/davidangulo/myapp/node_modules/react-native/scripts/react_native_pods.rb` would mean `/Users/davidangulo/myapp/node_modules/react-native` (parent of `scripts` folder).

While calling it on `ios/Podfile` would mean `/Users/davidangulo/myapp` (parent of `ios` folder)

---

This PR assumes that the default react native path is always the parent of the `scripts` folder. I also tested this PR on `RNTester` and it now works without `@prefix_path`.

I don't know how this will break monorepos or other setups since it doesn't matter where you store your `node_modules`. If the `scripts` folder is moved, the default react native path will also move.

@cipolleschi Let me know if I don't make sense.

2022-12-20 16:47 UTC, cipolleschi commented
Thanks for the explanation. It makes sense... at this point, I would also update [line 56](https://github.com/facebook/react-native/blob/8dbbac49ac470fc343fdb519162e80b0300baeae/scripts/react_native_pods.rb#L56) to make it consistent. What do you think?

2022-12-21 15:26 UTC, dcangulo commented
@cipolleschi Upon looking into it more, it seems like my solution creates a major side effect.

2022-12-21 15:26 UTC, closed without merging