Exclude `react-native-flipper` when `NO_FLIPPER=1` to prevent iOS build fail
facebook/react-native pull request #35686
Opened 2022-12-20 09:56 UTC by retyui

## Summary

iOS build fail with an error:

```sh
node_modules/react-native-flipper/ios/FlipperReactNativeJavaScriptPlugin.h:9:9: 'FlipperKit/FlipperConnection.h' file not found

#import <FlipperKit/FlipperConnection.h>
```

## Changelog

[IOS] [FIXED] - Exclude `react-native-flipper` when `NO_FLIPPER=1` to prevent iOS build fail

## Test Plan

```sh
npx react-native init RN0710RC5 --version 0.71.0-rc.5
cd RN0710RC5
yarn add react-native-flipper
NO_FLIPPER=1 pod install --project-directory=ios
yarn ios # will fail
```

2022-12-20 13:44 UTC, cipolleschi requested changes
Hi @retyui, thank you for the PR.

Can I ask you to expand on the use case, please?
In the repro, you are adding a library that depends on Flipper (`react-native-flipper`) and then you are NOT installing Flipper, by passing `NO_FLIPPER=1`. I think it is correct that the app doesn't build with that setup.

If you need to use `react-native-flipper`, you have to also install Flipper in your app (the default setup, or, in other words `NO_FLIPPER=0`). 

On a side note, the `react-native.config.js` is a configuration file specific for each project. It should not be responsibility of React Native to preconfigure it. Every app should be able to add it and customise it as they prefer. We don't want to prefill it with some default values: users may get confused why they need them and/or they may need to change it and React Native should not depend on some specific settings there.

2022-12-20 20:02 UTC, retyui commented
@cipolleschi that's a popular optimization  for developers to turn off Flipper on CI to speed up iOS builds, 

Previously it was a developer responsibility to add if CI condition to turn off it

But starting from `0.71.x` React Native team added it as core functional in `Podfile`, and I think it will be confusion that when build will fail if you define a`NO_FLIPPER=1`

So, to be more developer friendly we can add a comment about `react-native-flipper` (that it should be also excluded) 
if your thinking that adding a `react-native.config.js` it is a bad idea

2022-12-30 08:56 UTC, cipolleschi commented
> Previously it was a developer responsibility to add an if CI condition to turn off it

> But starting from 0.71.x React Native team added it as core functionality in Podfile, and I think it will be confusion when builds will fail if you define a NO_FLIPPER=1

And that's fine, but I if we add a reference to `react-native-flipper`, we are implicitly "adding a dependency" to that library for everyone. I think that the best solution is to document the `NO_FLIPPER` flag and suggest people how to handle libraries that depends on Flipper, but not to adding some specific configuration in the framework.

What do you think?

2023-01-02 09:50 UTC, artyorsh commented
I partially agree with proposed solution. But yeah, it should not be in template config as long as there is no `react-native-flipper` dependency listed in package.json. To follow-up on @cipolleschi, I think it is better to document the proposed solution leaving a comment on where/why would we need it.

The "why" that led me here was a use of flipper react-navigation plugin, which is dependent on react-native-flipper package.

2023-01-05 14:59 UTC, cipolleschi commented
Thanks for updating the PR. I'll proceed importing it and trying to land it.

Meanwhile, I also created this PR on the website: https://github.com/facebook/react-native-website/pull/3503
I think that the `Podfile` is not a very visible place where we can document this. The website could be more discoverable.

What do you think?

2023-01-05 14:59 UTC, cipolleschi approved these changes

2023-01-05 15:58 UTC, dmytrorykun commented
I agree that having a proposed solution in form of a comment inside `Podfile` is not very visible, nor helpful. Maybe make it a console message?

2023-01-05 16:01 UTC, retyui commented
We can throw an error on `pod install` when `NO_FLIPPER=1` and `react-native-flipper` pod was added

2023-01-05 16:17 UTC, dmytrorykun commented
@retyui Yes, warning is better than a hard error 👍

2023-01-05 16:23 UTC, retyui commented
Ok, then I close this PR and will open PR in `@react-native-community/cli`, won't it?

2023-01-05 16:37 UTC, dmytrorykun commented
@retyui We can probably also do it here https://github.com/facebook/react-native/blob/main/scripts/react_native_pods.rb#L211
```
if ReactNativePodsUtils.has_pod(installer, 'react-native-flipper') && ENV["NO_FLIPPER"] == "1"
  Pod::UI.warn " warning text "
end
```
@cipolleschi What do you think?

2023-01-05 17:04 UTC, cipolleschi commented
I personally don't think that the solution. `react-native-flipper` is one instance of the problem of a Library that depends on some Flipper pod. If we implement this warning, we can catch `react-native-flipper`, but devs may use other dependencies that depends on the Flipper pods and still encounter the issue.

I don't think that it is React Native responsibility to handle this problem in code. React Native exposes some dependencies, but we can't control what happens outside them. What we can do is to point users to the proper documentation (e.g.: https://github.com/facebook/react-native-website/pull/3503).

2023-01-05 20:50 UTC, retyui commented
Since `react-native-flipper` is currently the foundation for community plugins, why not display a caution notice with a link to the documentation page so we can recognize this scenario?

2023-01-06 08:46 UTC, cipolleschi commented
> why not display a caution notice with a link to the documentation page

We can do that, but where would you put the caution note? In the website PR there is the explicit example.

What we should actually do is to update the README.md of the `react-native-flipper` plug-in, explaining how to properly configure it.

2023-01-10 14:17 UTC, retyui commented
> What we should actually do is to update the README.md of the `react-native-flipper` plug-in, explaining how to properly configure it.

I don't believe updating the README.md of `react-native-flipper` would be helpful.

As usually developers install this modules as dev-tools required ( as that dccs. don't referring to the original Installation sections  of `react-native-flipper`, they just suggest `npm i react-native-flipper`)

As is typical, developers install this module when certain dev-tools are needed 

(because that docs. don't refer to the original "Installation" sections of `react-native-flipper`; it only recommends `npm I react-native-flipper`).

See:

![image](https://user-images.githubusercontent.com/4661784/211574112-8874a9e6-1c65-4bde-b23c-3ea5a1e5b5b0.png)

---

![image](https://user-images.githubusercontent.com/4661784/211573818-f3718776-8f1c-4ea4-9f83-134fb484cb30.png)

2023-01-12 10:36 UTC, cipolleschi commented
Thanks for the context. I have to think more about a proper solution, then.

2023-01-12 10:56 UTC, closed without merging