Fix/animated lists types
facebook/react-native pull request #36292
Opened 2023-02-25 07:52 UTC by JeongShin

## Summary

I was working on `Animated.FlatList` and found some types missing as below

![Screen Shot 2023-02-25 at 4 32 43 PM](https://user-images.githubusercontent.com/64301935/221345457-74252131-5207-4e17-ad96-92221a915305.png)

also `Animated.SectionList` 

![Screen Shot 2023-02-25 at 4 31 34 PM](https://user-images.githubusercontent.com/64301935/221345679-07ba862b-708e-400e-ac14-7d2156fcc1e8.png)

So I added type definition for `Animated.FlatList` and `Animated.SectionList` copied from `FlatList` types located at `Library/Lists/FlatList.d.ts`, `Library/Lists/SectionList.d.ts`.  

## Changelog

[GENERAL] [FIXED] - add missing FlatList types for Animated FlatList
[GENERAL] [FIXED] - add missing SectionList types for Animated SectionList

## Test Plan

Ran `yarn test-typescript` and `yarn test-typescript-offline` with no errors.

2023-02-27 14:30 UTC, NickGerleman requested changes
Can we factor this to reuse the imperative methods already defined for VirtualizedList, instead of duplicating this?

2023-02-27 16:10 UTC, JeongShin commented
> Can we factor this to reuse the imperative methods already defined for VirtualizedList, instead of duplicating this?

I tried to use `abstract class` to reuse the imperative methods. 
Thank you 🙇🏻‍♂️.

2023-02-27 19:06 UTC, carlosalmonte04 commented on Libraries/Animated/Animated.d.ts
> +import {NodeHandle} from '../ReactNative/RendererProxy';
`NodeHandle` is not in use.

2023-02-27 22:25 UTC, JeongShin commented on Libraries/Animated/Animated.d.ts
> +import {NodeHandle} from '../ReactNative/RendererProxy';
Removed unused type. thank you.

2023-02-28 20:25 UTC, carlosalmonte04 commented
Do you think it is a good idea to make changes only on `Animated.d.ts` and not change `Flatlist.d.ts` and `SectionList.d.ts`? Otherwise this looks good to me.

2023-02-28 21:28 UTC, JeongShin commented
> Do you think it is a good idea to make changes only on `Animated.d.ts` and not change `Flatlist.d.ts` and `SectionList.d.ts`? Otherwise this looks good to me.

I made changes only on `Animated.d.ts` to fix `Animated.FlatList` type definition not supporting `Animated.FlatList` method types which shares with FlatList. (scrollToIndex, scrollToItem, ... etc). 

So, I fixed `Animated.FlatList` to extends `FlatList` types including method types.

<img width="321" alt="Screen Shot 2023-03-01 at 6 22 15 AM" src="https://user-images.githubusercontent.com/64301935/221983352-3bf6cb88-a2db-4361-8b2f-b062db9db377.png">

2023-02-28 21:32 UTC, NickGerleman approved these changes

2023-02-28 23:21 UTC, closed without merging