fix(xcode): backport Xcode 14.3 fix to 69
facebook/react-native pull request #36767
Opened 2023-04-03 10:12 UTC by kelset

## Summary:

A quick attempt at a minimal fix for 0.69 for https://github.com/facebook/react-native/issues/36739, based on https://github.com/facebook/react-native/pull/36759

## Changelog:

[IOS] [FIXED] - Fix React Codegen podspec to build on Xcode 14.3

## Test Plan:

2023-04-03 10:34 UTC, cipolleschi requested changes

2023-04-03 10:34 UTC, cipolleschi commented on .circleci/config.yml
> +      xcode: &_XCODE_VERSION "14.3.0"
I will not change this as we don't have Ruby backward compatibility here and we are not really installing the right version of ruby.

2023-04-03 10:46 UTC, cipolleschi approved these changes

2023-04-03 15:01 UTC, merged

2023-04-03 18:55 UTC, focux commented
Awesome, when is this going to be released, or is there a quick fix that we can implement meanwhile?

2023-04-11 17:40 UTC, archcorsair commented
> Awesome, when is this going to be released, or is there a quick fix that we can implement meanwhile?

It has been released now