TS definition: Change StyleSheet.flatten return type to reflect its nullability
facebook/react-native pull request #36842
Opened 2023-04-06 17:15 UTC by yhkaplan

## Summary:

I realize this would be a breaking change and there may be better ways of addressing it, but in our codebase, we've been bitten by runtime exceptions due to overlooking the undefined case before, and a more precise type definition would help avoid that. Please tell me if you think there's a better strategy 🙏 

- Implementation: https://github.com/facebook/react-native/blob/main/packages/react-native/Libraries/StyleSheet/flattenStyle.js#L20-L22

## Changelog:

[GENERAL] [BREAKING] - Change StyleSheet.flatten return type to reflect its nullability

## Test Plan

Use type tests

2023-04-06 17:53 UTC, yhkaplan commented
Gotta fix type tests

<details>

```
yarn run v1.22.18
$ dtslint --localTs node_modules/typescript/lib  packages/react-native/types
dtslint@0.0.127
Error: /home/circleci/react-native/packages/react-native/types/__typetests__/index.tsx:218:25
ERROR: 218:25  expect  TypeScript@local compile error: 
Object is possibly 'undefined'.
ERROR: 233:22  expect  TypeScript@local compile error: 
Object is possibly 'undefined'.
ERROR: 234:22  expect  TypeScript@local compile error: 
Object is possibly 'undefined'.
ERROR: 235:23  expect  TypeScript@local compile error: 
Object is possibly 'undefined'.
ERROR: 236:29  expect  TypeScript@local compile error: 
Object is possibly 'undefined'.
ERROR: 241:8   expect  TypeScript@local compile error: 
Property 'top' does not exist on type 'ViewStyle | undefined'.

    at testTypesVersion (/home/circleci/react-native/node_modules/@definitelytyped/dtslint/dist/index.js:194:15)
    at async runTests (/home/circleci/react-native/node_modules/@definitelytyped/dtslint/dist/index.js:151:9)
    at async main (/home/circleci/react-native/node_modules/@definitelytyped/dtslint/dist/index.js:79:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Failed to run TypeScript tests.
Finished.
/home/circleci/react-native/scripts/run-ci-javascript-tests.js:99
    throw Error(exitCode);
    ^

Error: 1
    at Object.<anonymous> (/home/circleci/react-native/scripts/run-ci-javascript-tests.js:99:11)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

</details>

2023-04-07 04:52 UTC, NickGerleman commented
Re the breaks, would it be possible to define the return type based on the type of the generic input? I.e. the return type allows undefined only if the input parameter extends null or undefined?

2023-04-07 04:57 UTC, NickGerleman commented
That change does at some inconsistency with the flow type which is nullable, but I think inferring nullability is strictly more permissive than the current flow type. So, both Flow and TS could use that approach, without really breaking either (except for the case in TS where the input is nullable).

2023-04-07 17:47 UTC, yhkaplan commented
> Re the breaks, would it be possible to define the nullability of the return type based on the type of the generic input? I.e. the return type allows undefined only if the input parameter extends null or undefined?

It didn't look possible with generics, but with overloads I could make the properties of the flattened object optional instead of the flattened object itself, which is nicer to use. I updated the tests to make it clearer what types the properties become.

2023-04-08 04:44 UTC, NickGerleman requested changes

2023-04-08 04:44 UTC, NickGerleman commented on packages/react-native/Libraries/StyleSheet/StyleSheet.d.ts
> +  export function flatten(style: undefined): undefined;
Should the input also accept null?

2023-04-08 04:44 UTC, NickGerleman commented on packages/react-native/types/__typetests__/index.tsx
> +const welcomeFontSize: number | undefined = StyleSheet.flatten(
These should no longer be possibly undefined, right?

2023-04-08 04:44 UTC, NickGerleman commented on packages/react-native/types/__typetests__/index.tsx
> +const undefinedStyle: undefined = StyleSheet.flatten(undefined);
Could we test against a nullable style prop  instead of just undefined, so we validate the right overload is used?

2023-10-12 05:23 UTC, closed without merging