Adding cursor coordinates to TextInput
facebook/react-native pull request #36979
Opened 2023-04-19 15:39 UTC by perunt

## Summary:

## Changelog:

## Test Plan:

2023-06-07 13:58 UTC, cortinico requested changes
Hey @perunt 
Can you please take a look at the CI signal as the Android code is not compiling

2023-06-09 11:54 UTC, perunt commented
Now it's compiling successfully, and all tests are passing well. Please let me know if you notice any other issues.

2023-06-09 16:20 UTC, acoates-ms commented
Can you add a RNTester page or add to an exisiting one, a usage of the new API?
I dont see the new properties added to the type information in the JS?  I'd expect to see an update to TextInput.js's Selection type, and a matching change in TextInput.d.ts.

2023-06-09 16:21 UTC, acoates-ms commented
I suspect this also needs some changes in fabric to support the extra properties?

2023-06-10 01:23 UTC, NickGerleman commented
Yes, I think previously the RN team had decided we will not be taking new props with only a Paper implementation, since it means these will stop working the moment we switch to Fabric as the default.

2023-06-10 01:29 UTC, NickGerleman commented
I would also expect this series of changes to include both Flow and TypeScript types. Right now using this API would require suppressing typecheking errors.

2023-06-14 09:05 UTC, perunt commented
Got it, let me address all this stuff

2023-06-14 22:10 UTC, PPatBoyd commented
Would it make sense for the caret position to be a pair of points / rect?  What point does the current XY represent?

2023-06-15 18:59 UTC, perunt commented on packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputSelectionEvent.java
> +    this(-1, viewId, selectionStart, selectionEnd, cursorPositionX, cursorPositionY);
I used an old code version before `NO_SURFACE_ID` was implemented (https://github.com/facebook/react-native/commit/d2d2a8a598cb8b5e5218c3c21cef408de2142fe4)
I'll update it

2023-06-15 19:26 UTC, perunt commented
The XY is just pointing to the top-left start of the selection right now. I get what you're saying - it might be a good move to add the end point too.

2023-06-16 17:18 UTC, acoates-ms commented
> The XY is just pointing to the top-left start of the selection right now. I get what you're saying - it might be a good move to add the end point too.

I'm not sure what you are doing with these coords, but many of the use cases I can think of would require having both topleft and bottom right coords.  Want to show a menu at the cursor? - depending on if the menu is going to show above or below the cursor, you'd need both coords.

2023-06-16 19:28 UTC, perunt commented
> I'm not sure what you are doing with these coords, but many of the use cases I can think of would require having both topleft and bottom right coords. Want to show a menu at the cursor? - depending on if the menu is going to show above or below the cursor, you'd need both coords.

Yes, my goal is to use this for menu positioning. I've attempted using both coordinates as you've suggested, but encountered a bit of a hiccup when it came to selection. I've been considering whether it should just pinpoint to a single location instead.
I can do the two-coordinates thing. Do you reckon I should do the same with the selection? I mean, if there were a few lines of selection, it would show the top left and bottom right corner coordinates,

2023-06-20 11:54 UTC, perunt commented
@Szymon20000 will appreciate any thoughts on it, thanks!

2023-06-20 21:09 UTC, NickGerleman requested changes
It looks like this does not implement the change on iOS Fabric at least (did a quick check that `RCTTextInputComponentView` does not reuse the view edited).

This change seems fairly mechanical, but we usually ask folks to split these sorts of PRs, to enable finding the most appropriate reviewers for each part (and to make it easy to ship things as they become ready). Right now we have:
1. New event data, and new prop
2. Android, iOS, and JS layer changes
3. Paper and Fabric support (these may end up being the same on Android)

If this change gets much larger, I think we will want to split this up a bit, and might actually recommend we do that for the next iteration (e.g. separate PRs for Android and iOS).

I have not looked closely at the implementation for this yet, but the other questions I had were around the new API to allow explicitly controlling cursor position. I don't see this mentioned in your description, but I am curious how explicit control of cursor position interacts with character index based selection. Are these independent?

2023-06-22 19:33 UTC, perunt commented
> I have not looked closely at the implementation for this yet, but the other questions I had were around the new API to allow explicitly controlling cursor position. I don't see this mentioned in your description, but I am curious how explicit control of cursor position interacts with character index based selection. Are these independent?

Thanks for the feedback! So, about that cursor position - It updates when the `onSelectionChanged` event fires and it doesn't refresh when we explicitly set the selection. 
Now, about the Fabric support, yep, I dropped the ball there. I was testing on a fork from the main and completely spaced on checking if changing the flag really turned Fabric. Good catch! I'm on it - will set up new PRs for Android and iOS Fabric support asap.

2023-07-04 11:20 UTC, perunt commented
iOS - In this pr (https://github.com/facebook/react-native/pull/38110), I've added Fabric support and fixed the coordinates update when controlling cursor position explicitly.

Android - In this pr (https://github.com/facebook/react-native/pull/38123), It works with Fabric support and has the same updates for coordinates.

I've separated these for iOS and Android for better code review. However, I'm unsure how to handle the JavaScript portion as it's part of the example. @NickGerleman should I create separate pull requests for iOS fabric and paper?

2023-08-02 08:51 UTC, perunt commented
@NickGerleman all necessary updates made in that PRs

> iOS - In this pr (https://github.com/facebook/react-native/pull/38110), I've added Fabric support and fixed the coordinates update when controlling cursor position explicitly.
Android - In this pr (https://github.com/facebook/react-native/pull/38123), It works with Fabric support and has the same updates for coordinates.

Current PR I'll leave for grouping this issue

2024-03-05 05:23 UTC, closed without merging