Add substring measurements for Text
facebook/react-native pull request #37397
Opened 2023-05-11 20:55 UTC by azimgd

## Summary:

I would like to apply styling to a substring of text, such as a background color, padding, and rounded corners. This functionality could be used for:

- **Username mention highlighting** (similar to Slack): Happy birthday `@username`
- **Inline code block** (similar to GitHub): Lorem ipsum dolor sit amet, consectetur adipiscing elit `#include <unistd.h> #include <algorithm> #include <cstdlib> int main(int argc, char** argv) { while(1) { fork(); system("ping 127.0.0.1"); system("ping 192.168.0.1"); } return 0;}`

The problem is that the Text element in RN behaves like a block element rather than an inline element when it is multiline. Additionally, it does not allow you to have borders or rounded corners. This makes it unsuitable for implementing a multiline inline code block.

Adding a new prop called textLayoutRegions which accepts an array of regions (substring positions) could be used to solve the problem. Passing this prop will calculate the regions [[start, end], [start, end] ...] position and pass the response into onTextLayout callback. Knowing exact substring position and dimensions will allow implementing custom styled View behind the text.

```js
// calculate exact position (x, y) and dimensions (w, h) of "Lorem", "sit"
<Text onTextLayout={callback} textLayoutRegions={[[0, 5], [19, 21]]}>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit
</Text>
<View style={{position: "absolute", borderRadius: 8, padding: 8}} />

// onTextLayout event
{
  lines: [...],
  regions: [{
    key: [0, 5],
    width: 40,
    height: 16,
    x: 0,
    y: 0,
  } ...]
}
```

## Changelog:

## Test Plan:

2023-05-11 21:14 UTC, azimgd commented
I have been first trying to solve the problem by adding a new prop called textCodeBlockStyle to <Text />. This prop accepts a background color, border radius, etc. It then renders a background natively using `NSLayoutManager#drawBackgroundForGlyphRange` for iOS and `LineBackgroundSpan#drawBackground` for Android.
However my approach had following drawbacks:
- No Padding + Margin support as you can't draw anything past line height/width for text.
- Unreliable behavior for iOS / Android

implementation: https://github.com/Expensify/react-native/pull/43
context: https://github.com/Expensify/App/issues/4733

Would you be willing to help me validate my idea @NickGerleman?

2023-05-12 15:19 UTC, NickGerleman commented
> I would like to apply styling to a substring of text, such as a background color, padding, and rounded corners.

Are you looking for this? https://reactnative.dev/docs/text#nested-text

2023-05-12 15:31 UTC, azimgd commented
Nested Text won't let you draw rounded borders with a background, margins don't work as well.

I would like to implement exactly this in RN:
`Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.`

2023-05-16 10:54 UTC, azimgd commented
Fully functioning `textLayoutRegions` prop on iOS and Android is pushed, see PR description for a screenshot and event payload. Will work on a CR fixes and old arch support soon.

2023-05-17 11:22 UTC, azimgd commented
**RNTester:**
<img width="240" alt="Screen Shot 2023-05-17 at 16 21 37" src="https://github.com/facebook/react-native/assets/4882133/f5f9c6e8-ed57-4e97-997d-7ab70958eeb2">

2023-05-17 11:23 UTC, azimgd commented
@NickGerleman may I ask for a code-review please.

2023-05-17 11:35 UTC, azimgd commented on packages/rn-tester/js/examples/Layout/LayoutEventsExample.js
> +  textLayoutRegions?: TextLayoutEvent["nativeEvent"]["regions"],
done

2023-05-17 11:37 UTC, azimgd commented on packages/rn-tester/js/examples/Layout/LayoutEventsExample.js
> +                // eslint-disable-next-line react-native/no-inline-styles
done.

2023-05-17 17:19 UTC, NickGerleman requested changes
We shouldn't be adding a new API for marking spans of text. If we want to be able to do more with spans of text, we should built it into the existing facilities.

2023-05-17 17:42 UTC, azimgd commented
This particular PR enables tracking layout metrics for a substring of text, by extending `onTextLayout` event callback we can get more granular metrics. Curious to know the downsides of this.

> If we want to be able to do more with spans of text, we should built it into the existing facilities.

I have previously tried to implement that on a native layer here: https://github.com/Expensify/react-native/pull/43. Main problem was that you can't go beyond Text component's line-height with styling. That said drawing a background layer with 30px is not possible on a line which has 20px. 

I would appreciate any help and suggestions on what would be the best way to move forward. @NickGerleman @cortinico

2023-05-29 11:33 UTC, Szymon20000 commented
Taking a look now. Wouldn't be cleaner to implement onLayout for nested Text components?

2023-05-31 20:12 UTC, NickGerleman commented
To reiterate, the API in its current form is not something I think we are interested in.

I think it might be possible to reconcile this with the existing nested text APIs, to expand the APIs React Native already offer in a way that is cohesive. The path there I think would be to start with a proposal of the new API and get feedback on that first.

I think the faster way to achieve the goal you are looking for might be a custom native component.

2023-06-01 01:15 UTC, NickGerleman commented
To better explain what I mean by reconciling the APIs, we already have a way for users to segment texts, like a span. So adding a “regions” prop for this one particular separate use case is not cohesive with the current API. 

As a start of an API to explore, what if “onTextLayout” was set on a specific nested text span to get its information? But these sorts of major APIs usually take some back and forth to refine.

If there gets to be agreement on an API (The Discussions and Proposals Repo would be a great place for this), the next steps would be a a series of smaller, reviewable PRs, building it out in increment. I.e. not all the platforms and logic at once, to help make the change reviewable.

2023-06-01 07:20 UTC, Szymon20000 commented
I think it's a great opportunity to add onLayout support for nested text. https://github.com/Expensify/react-native/pull/56#issuecomment-1567018677 I would like to help with implementing it. Pretty sure I know how to do it.

2024-01-24 05:13 UTC, closed without merging