Exclude trailing whitespace on measuring text width
facebook/react-native pull request #37590
Opened 2023-05-26 11:40 UTC by bernhardoj

## Summary:

Multiline text in Android shows some extra space. It's easily noticeable when you set the text `alignSelf` to `flex-start`. This is because we are using `layout.getLineWidth` which will include trailing whitespace.
<img width="300" alt="image" src="https://github.com/facebook/react-native/assets/50919443/8939092b-caef-4ad8-9b34-2ccef5d20968">

Based on Android doc, `getLineMax` exclude trailing whitespace.
<img width="625" alt="image" src="https://github.com/facebook/react-native/assets/50919443/0b32e842-5fab-4fc7-8fd9-299877b9c553">

## Changelog:

[ANDROID] [FIXED] - Exclude trailing whitespace on measuring text width

## Test Plan:

After applying the changes:
<img width="300" alt="image" src="https://github.com/facebook/react-native/assets/50919443/bfbf52b0-7e7d-4c89-8958-6af38d8bc1c7">

Code snippet:
```
<Text style={{backgroundColor: 'red', alignSelf: 'flex-start', color: 'white'}}>
    1{'\n'}
</Text>
```

2023-05-27 00:46 UTC, NickGerleman commented
Why do we believe the current behavior is not the correct one?

2023-05-27 00:48 UTC, NickGerleman requested changes
Want to know more about why we think the previous behavior is incorrect, and the new behavior is correct

2023-05-27 05:01 UTC, bernhardoj commented
@NickGerleman Hi, thanks for taking a look. There are 2 reasons why I believe the current behavior is incorrect.

1. iOS does not have the extra space width
<img width="200" alt="image" src="https://github.com/facebook/react-native/assets/50919443/2b7e9542-984b-4814-9989-7b01634b6cd4">

2. Neither the native Android app.
<img width="200" alt="image" src="https://github.com/facebook/react-native/assets/50919443/decc4197-5218-4c7e-a3ea-cc036a4c8dc3">

---
However, I found a potential issue with the current changes I proposed. My initial intention is to remove extra width from the new line in multiline text, but it will also remove whitespace in multiline text without new line character.

For example, a case where the text is very long that it wraps to the next line. Below is the current behavior:
<img width="100" alt="image" src="https://github.com/facebook/react-native/assets/50919443/a62d8aa1-f442-4d4f-b82c-21d4dab448d0">

With the proposed changes, it will look like this:
<img width="100" alt="image" src="https://github.com/facebook/react-native/assets/50919443/385983b6-0516-487b-9a53-1a396216057f">

I think it's a potential issue because both iOS and native Android have the same behavior as we currently have on RN Android.

So, I was thinking to conditionally use `getLineMax` and `getLineWidth`. If the line ends with new line, we use `getLineMax`.
```
boolean endsWithNewLine = text.charAt(layout.getLineEnd(lineIndex) - 1) == '\n';
float lineWidth =
    endsWithNewLine
        ? layout.getLineMax(lineIndex)
        : layout.getLineWidth(lineIndex);
```

I see Android TextView do a similar thing here by using `getLineMax` if all the lines ends with new line.
https://android.googlesource.com/platform/frameworks/base/+/jb-mr0-release/core/java/android/widget/TextView.java#5931
<img width="350" alt="image" src="https://github.com/facebook/react-native/assets/50919443/bfa02419-3d6b-4bfc-aa9b-ffe27b233213">

Let me know if you agree with that.

2023-05-31 02:40 UTC, bernhardoj commented
If the line does not end with a new line character, we will use `getLineWidth`, so the spaces will be included.

But `getLineMax` actually will also include the whitespace if its the last line of the text.
https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/text/Layout.java#1726

2023-05-31 17:04 UTC, NickGerleman commented
That makes sense. The specific case that I think would be worth double checking for consistency against EditText and iOS TextInput is how we measure when we have a single line ending in spaces.

E.g. "foo   "

Under this new logic, I think we would terminate the end whitespace off of this, which is another behavior change to double check for consistency.

2023-06-01 07:48 UTC, bernhardoj commented
Sorry, I'm trying to understand but I don't quite get what (or how) to check from the TextInput 😅.

(I'm guessing we want to measure the TextInput content width through onContentSizeChange?)

2023-06-02 00:44 UTC, NickGerleman commented
Sorry, I misspoke when I said EditText/TextInput.

I just would like to see your screenshots above, but instead of a single line ending in a beeline, a single line ending in multiple spaces.

2023-06-02 03:48 UTC, bernhardoj commented
Ah, got it. 

Looks like both Android and iOS (RN) trim the whitespace. This is how it looks having a text `test    `.
<img width="164" alt="image" src="https://github.com/facebook/react-native/assets/50919443/544c0a82-79b2-4947-979d-21f3a3cd7d09">

Same result with the proposed changes.

So, are we good to use this new logic?
> So, I was thinking of conditionally using getLineMax and getLineWidth. If the line end with a new line, we use getLineMax. getLineMax will include whitespace if it ends with a new line.
>
> ```
>boolean endsWithNewLine = text.charAt(layout.getLineEnd(lineIndex) - 1) == '\n';
>float lineWidth =
>    endsWithNewLine
>        ? layout.getLineMax(lineIndex)
>        : layout.getLineWidth(lineIndex);
>```

2023-06-02 04:27 UTC, NickGerleman commented
That makes sense to me.

2023-06-02 09:11 UTC, bernhardoj commented
Pushed the new logic!

2023-06-06 11:47 UTC, bernhardoj commented
@NickGerleman please let me know if there are anything more I need to do to merge this one!

2023-06-06 22:44 UTC, NickGerleman approved these changes

2023-06-08 19:18 UTC, closed without merging

2023-06-09 01:34 UTC, NickGerleman commented
@bernhardoj it looks like we have to unland this change due to it causing the following error:

```
java.lang.IndexOutOfBoundsException: charAt: -1 < 0
	at android.text.SpannableStringBuilder.charAt(SpannableStringBuilder.java:122)
	at com.facebook.react.views.text.ReactTextShadowNode$1.measure(ReactTextShadowNode.java:138)
	at com.facebook.yoga.YogaNodeJNIBase.measure(YogaNodeJNIBase.java:522)
	at com.facebook.yoga.YogaNative.jni_YGNodeCalculateLayoutJNI(Native Method)
	at com.facebook.yoga.YogaNodeJNIBase.calculateLayout(YogaNodeJNIBase.java:220)
	at com.facebook.react.uimanager.ReactShadowNodeImpl.calculateLayout(ReactShadowNodeImpl.java:466)
	at com.facebook.react.uimanager.UIImplementation.calculateRootLayout(UIImplementation.java:941)
	at com.facebook.react.uimanager.UIImplementation.updateViewHierarchy(UIImplementation.java:662)
	at com.facebook.react.uimanager.UIImplementation.dispatchViewUpdates(UIImplementation.java:623)
	at com.facebook.react.uimanager.UIManagerModule.onBatchComplete(UIManagerModule.java:722)
	at com.facebook.react.bridge.NativeModuleRegistry.onBatchComplete(NativeModuleRegistry.java:140)
	at com.facebook.react.bridge.CatalystInstanceImpl$BridgeCallback.onBatchComplete(CatalystInstanceImpl.java:174)
	at com.facebook.jni.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loop(Looper.java:223)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
	at java.lang.Thread.run(Thread.java:923)
```

2023-06-09 03:54 UTC, bernhardoj commented
@NickGerleman My bad. I should have tested it with empty text. I can reproduce the crash in 2 cases:
1. Run the app in non-fabric (it's fine in fabric, empty text will be 'I')
2. Use `onTextLayout` on an empty text

If it's empty, `layout.getLineEnd` will return 0, and we subtract it with 1, we get -1. I would like to ask for an advise before opening the new PR. Which one do you think is a better fix for this:

1. Check if text is not empty
```
boolean endsWithNewLine = text.length() > 0 && text.charAt(layout.getLineEnd(i) - 1) == '\n';
```

2. Use Math.max
```
boolean endsWithNewLine = text.charAt(Math.max(0, layout.getLineEnd(i) - 1)) == '\n';
```

2023-06-09 04:31 UTC, NickGerleman commented
Subjectively I think the first option is easier to follow.

2023-06-09 04:37 UTC, bernhardoj commented
I agree. It's easier to understand the first option. Will open the new PR in a few moments!