Convert ImageStoreManagerTest.java to Kotlin
facebook/react-native pull request #37737
Opened 2023-06-06 18:35 UTC by megatunger

## Summary:

Converts ImageStoreManagerTest.java to Kotlin, as per issue https://github.com/facebook/react-native/issues/37708

## Changelog:

[Internal] [Changed] - Convert ImageStoreManagerTest.java to Kotlin

## Test Plan:

Tests pass: ./gradlew :packages:react-native:ReactAndroid:test
Formatted with [KtFmt](https://facebook.github.io/ktfmt/)

2023-06-06 20:24 UTC, megatunger commented
Hi @cortinico @mdvacca, Can you review this?

2023-06-07 09:20 UTC, cortinico requested changes
Thanks for sending this @megatunger 

I've left some comments that needs to be addressed before we can merge this. Thanks for doing this work.

2023-06-07 09:20 UTC, cortinico commented on packages/react-native/ReactAndroid/src/test/java/com/facebook/react/modules/camera/ImageStoreManagerTest.kt
> +import android.util.Base64
As mentioned above:

```suggestion
package com.facebook.react.modules.camera

import android.util.Base64
```

2023-06-07 09:20 UTC, cortinico commented on packages/react-native/ReactAndroid/src/test/java/com/facebook/react/modules/camera/ImageStoreManagerTest.kt
> +  }
+1 for doing this 👍

2023-06-07 09:20 UTC, cortinico commented on packages/react-native/ReactAndroid/src/test/java/com/facebook/react/modules/camera/ImageStoreManagerTest.kt
> +  }
```suggestion
  private fun invokeConversion(inputStream: InputStream): String? =
    imageStoreManager.convertInputStreamToBase64OutputStream(inputStream)
```

2023-06-07 09:20 UTC, cortinico commented on packages/react-native/ReactAndroid/src/test/java/com/facebook/react/modules/camera/ImageStoreManagerTest.kt
> +  private fun generateRandomByteString(length: Int): ByteArray? {
Let's move all the `private` methods at the end after all the tests?

2023-06-07 09:20 UTC, cortinico commented on packages/react-native/ReactAndroid/src/test/java/com/facebook/react/modules/camera/ImageStoreManagerTest.kt
> +    for (i in 0 until length) {
```suggestion
    repeat(length) {
```

2023-06-07 19:26 UTC, megatunger commented
Hi @cortinico, thanks for your review. I updated them, can you take a look again?

2023-06-08 08:29 UTC, cortinico approved these changes

2023-06-08 14:22 UTC, closed without merging