Migrate MultipartStreamReaderTest to Kotlin
facebook/react-native pull request #37743
Opened 2023-06-06 22:23 UTC by brunohensel

## Summary:

Migrate [MultipartStreamReaderTest.java](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/devsupport/MultipartStreamReaderTest.java) to Kotlin.  See #37708 

## Changelog:

[INTERNAL] [CHANGED] - Migrate MultipartStreamReaderTest to Kotlin

## Test Plan:

Tests pass: ./gradlew :packages:react-native:ReactAndroid:test
Formatted with [KtFmt](https://facebook.github.io/ktfmt/)

2023-06-07 10:11 UTC, cortinico requested changes
Thanks for sending this @brunohensel 

I've left some comments that needs to be addressed before we can merge this. Thanks for doing this work.

2023-06-07 10:11 UTC, cortinico commented on packages/react-native/ReactAndroid/src/test/java/com/facebook/react/devsupport/MultipartStreamReaderTest.kt
> +  @Throws(IOException::class)
Also this can go (on all the tests)

2023-06-07 10:11 UTC, cortinico commented on packages/react-native/ReactAndroid/src/test/java/com/facebook/react/devsupport/MultipartStreamReaderTest.kt
> +      ("preable, should be ignored\r\n" +
```suggestion
      ("preamble, should be ignored\r\n" +
```

2023-06-07 10:35 UTC, brunohensel commented on packages/react-native/ReactAndroid/src/test/java/com/facebook/react/devsupport/MultipartStreamReaderTest.kt
> +    @Throws(IOException::class)
Yeah, my bad! ^^

2023-06-07 10:57 UTC, brunohensel commented on packages/react-native/ReactAndroid/src/test/java/com/facebook/react/devsupport/MultipartStreamReaderTest.kt
> +      ("preable, should be ignored\r\n" +
A question, I saw that the [implementation](https://github.com/facebook/react-native/blob/08dc0a63ce6f0fbd3b57db18ed6b98f57e7195a5/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/devsupport/MultipartStreamReader.java#L20) depends on the `\r\n` line separator. I'm not sure if using a multiline string (removing explicitly those line separators) will work. At least, when I approached it with the multiline, the tests fail.

2023-06-08 18:33 UTC, mdvacca approved these changes
lgtm

2023-06-09 08:11 UTC, cortinico approved these changes

2023-06-09 13:32 UTC, closed without merging