Convert NativeAnimatedInterpolationTest to Kotlin
facebook/react-native pull request #37742
Opened 2023-06-06 21:19 UTC by fabioh8010

## Summary:

This PR converts NativeAnimatedInterpolationTest.java to Kotlin as requested in [this issue](https://github.com/facebook/react-native/issues/37708).

## Changelog:

[INTERNAL] [CHANGED] - Convert NativeAnimatedInterpolationTest to Kotlin

## Test Plan:

1. Run `./gradlew :packages:react-native:ReactAndroid:test`.
2. All tests should pass.

2023-06-06 21:20 UTC, fabioh8010 commented
@cortinico and @mdvacca could you please review? Thanks!

2023-06-07 09:33 UTC, cortinico requested changes
Thanks for sending this @fabioh8010 

I've left some comments that needs to be addressed before we can merge this. Thanks for doing this work.

2023-06-07 09:33 UTC, cortinico commented on packages/react-native/ReactAndroid/src/test/java/com/facebook/react/animated/NativeAnimatedInterpolationTest.kt
> +    return InterpolationAnimatedNode.interpolate(
```suggestion
  ): Double = InterpolationAnimatedNode.interpolate(
```

2023-06-07 09:33 UTC, cortinico commented on packages/react-native/ReactAndroid/src/test/java/com/facebook/react/animated/NativeAnimatedInterpolationTest.kt
> +  private fun simpleInterpolation(
Let's move this private method at the bottom of the class after all the tests?

2023-06-07 09:33 UTC, cortinico commented on packages/react-native/ReactAndroid/src/test/java/com/facebook/react/animated/NativeAnimatedInterpolationTest.kt
> +    val output = intArrayOf(-0x1000000, -0x10000)
Not a big fan of this conversion.
Can we use instead:

```
0xFF000000.toInt()
```

and make sure the original hex values are preserved? (valid for the whole test)

2023-06-08 07:24 UTC, mdvacca approved these changes
lgtm

2023-06-08 08:30 UTC, cortinico approved these changes
LGTM 👍

2023-06-08 17:46 UTC, closed without merging