feat: Resolve gradle files dynamically
facebook/react-native pull request #38702
Opened 2023-07-31 14:35 UTC by Esemesek

## Summary:

Files inside `node_modules` aren't always present in exact locations specified in `gradle` configuration. Impacted projects:
- Projects using package managers like `pnpm`
- Might be the case for projects with non-standard directory structures

To fix this issue we can simply use Node mechanism to resolve modules (`require.resolve`).

This PR is blocking https://github.com/react-native-community/cli/pull/2036

## Changelog:

## Test Plan:

1. Initialise a new project using this template
2. Build `android` project

2023-08-01 15:09 UTC, cortinico commented on packages/react-native/template/android/utils.gradle
> +ext.resolveJSModule = { String path ->
We won't be adding yet another `.gradle` file inside the template (we're actually trying to remove them so this change goes in the wrong direction).

2023-08-01 15:12 UTC, cortinico requested changes
Thanks for sending this over @Esemesek 

Sadly we can't accept this change as it for a number of reasons:
1. We don't want to have `require.resolve()` call in user space (they should be inside the Gradle Plugin or inside the CLI code).
2. We don't want to have another file included in the template (we're actually trying to remove them).
3. The module resolution is actually incorrect as you should resolve `@react-native-community/cli-platform-android` from the `react-native` resolution path (and not root).

2023-08-01 15:34 UTC, Esemesek commented
1. Not sure how it would work. The whole point of this is to resolve `CLI` files correctly. We already have similar mechanism in the template for Cocoapods - https://github.com/facebook/react-native/blob/main/packages/react-native/template/ios/Podfile#L2
2. Can be done, but some of the things will have to be duplicated unless there is another way to share functions between gradle configuration files.
3. Pretty sure the module resolution is okay here. The current path to the gradle file points to the root `node_module` directory.

2023-08-02 09:43 UTC, byCedric commented
I can chime in on point 3 here. The proposed resolution is incorrect due to the default pnpm behavior, the concept of "[isolated modules](https://github.com/npm/rfcs/blob/main/accepted/0042-isolated-mode.md)".

The main difference between the behavior of this isolated module, and let's say "normal" package managers like yarn v1, is that the `node_modules` folder behaves more like a graph datatype instead of a list.

If you install `react-native` in an empty pnpm project, you can see what's happening:

- `$ npm install -g pnpm@latest`
- `$ pnpm init`
- `$ pnpm add react-native`

This would create a `node_modules` folder that looks like:

```
node_modules
  .pnpm         -> A store containing all downloaded packages and versions
  .modules.yaml -> Pnpm internal file describing each package and if they are installed "publicly" or "privately"
  react-native  -> A symlink to the `.pnpm/...` path where `react-native` is actually installed
```

As you should be able to see, only `react-native` is linked directly inside `node_modules`. Meaning that if you were to run `node --print "require.resolve('react-native')"` from the project root, it should resolve the location.

Here is where the interesting part comes in, only direct project dependencies (deps listed inside the user's `package.json`) are linked in the `node_modules`. All nested dependencies are only accessible from the packages they are requested from.

In this PR, you added the following resolutions in the template, and thus user code:

```
def nativeModulesPath = resolveJSModule('@react-native-community/cli-platform-android/native_modules.gradle')
def gradlePluginPath = resolveJSModule('@react-native/gradle-plugin/package.json').replace('/package.json', '')
```

But neither `@react-native-community/cli-platform-android` or `@react-native/gradle-plugin` should be a direct project dependency. Instead, it's requested from the `react-native` package. So, `node --print require.resolve('@react-native/gradle-plugin')` from the project root will fail.

To "properly" resolve this and be compliant with isolated modules, we have to resolve the whole dependency chain. Something like this (pseudo code):
`require resolve "react-native" > "@react-native/gradle-plugin"`

> Note that resolutions within the `react-native` package, or other dependencies, should start from the installation location of the dependency itself. So instead of just running the `require.resolve(...)` command from anywhere, it should explicitly say `require.resolve(..., paths: [__dirname])` - or at least force the `cwd` to the installation location of the package before running the `require.resolve` command.

2023-08-07 09:04 UTC, closed without merging