☂️ RNTesterReactHostDelegate.java => RNTesterReactHostDelegate.kt
facebook/react-native pull request #38877
Opened 2023-08-09 07:11 UTC by fabiansolheim

## Summary:

This PR converts RNTesterReactHostDelegate into Kotlin as requested in https://github.com/facebook/react-native/issues/38825 .

## Changelog:

[INTERNAL] [CHANGED] - Convert to RNTesterReactHostDelegate.java => Kotlin

## Test Plan:

Run yarn && yarn android
All tests should pass

2023-08-09 09:23 UTC, fabiansolheim commented
@cortinico @mdvacca ready for review😀

2023-08-09 13:23 UTC, cortinico requested changes
Hey @fabiansolheim 
Thanks for sending this over,
there are several changes that you need to apply before we can merged this

2023-08-09 13:23 UTC, cortinico commented on packages/rn-tester/android/app/src/main/java/com/facebook/react/uiapp/RNTesterReactHostDelegate.kt
> +  private var mReactPackages: List<ReactPackage> = emptyList()
```suggestion
  var reactHost: ReactHost? = null
  private var reactPackages: List<ReactPackage> = emptyList()
```

2023-08-09 13:23 UTC, cortinico commented on packages/rn-tester/android/app/src/main/java/com/facebook/react/uiapp/RNTesterReactHostDelegate.kt
> +class RNTesterReactHostDelegate internal constructor(private val mContext: Context) :
```suggestion
internal class RNTesterReactHostDelegate(private val context: Context) :
```

2023-08-09 13:23 UTC, cortinico commented on packages/rn-tester/android/app/src/main/java/com/facebook/react/uiapp/RNTesterReactHostDelegate.kt
> +  }
this can go

2023-08-09 13:23 UTC, cortinico commented on packages/rn-tester/android/app/src/main/java/com/facebook/react/uiapp/RNTesterReactHostDelegate.kt
> +    get() = "js/RNTesterApp.android"
```suggestion
  override val jSMainModulePath: String = "js/RNTesterApp.android"
```

2023-08-09 13:23 UTC, cortinico commented on packages/rn-tester/android/app/src/main/java/com/facebook/react/uiapp/RNTesterReactHostDelegate.kt
> +      if (mReactHost!!.jsEngineResolutionAlgorithm == JSEngineResolutionAlgorithm.JSC) {
Use `.?` instead

2023-08-09 13:23 UTC, cortinico commented on packages/rn-tester/android/app/src/main/java/com/facebook/react/uiapp/RNTesterReactHostDelegate.kt
> +  }
```suggestion
  override fun getReactNativeConfig(turboModuleManager: TurboModuleManager): ReactNativeConfig = ReactNativeConfig.DEFAULT_CONFIG
```

2023-08-09 13:23 UTC, cortinico commented on packages/rn-tester/android/app/src/main/java/com/facebook/react/uiapp/RNTesterReactHostDelegate.kt
> +      if (mReactPackages == null) {
`if (reactPackages.isEmpty())` ...

2023-08-09 13:23 UTC, cortinico commented on packages/rn-tester/android/app/src/main/java/com/facebook/react/uiapp/RNTesterReactHostDelegate.kt
> +          Arrays.asList(
This is Java specific and should be converted to the Kotlin equivalent

2023-08-09 13:23 UTC, cortinico commented on packages/rn-tester/android/app/src/main/java/com/facebook/react/uiapp/RNTesterReactHostDelegate.kt
> +              }
```suggestion
              override fun createNativeModules(
                reactContext: ReactApplicationContext
              ): List<NativeModule> = emptyList()
```

2023-08-09 13:23 UTC, cortinico commented on packages/rn-tester/android/app/src/main/java/com/facebook/react/uiapp/RNTesterReactHostDelegate.kt
> +              }
```suggestion
              ): List<ViewManager<*, *>> = listOf(MyNativeViewManager(), 
 MyLegacyViewManager(reactContext))
```

2023-08-09 16:42 UTC, cortinico commented on packages/rn-tester/android/app/src/main/java/com/facebook/react/uiapp/RNTesterReactHostDelegate.kt
> +              }
This whole block could be simplified to just return a `mapOf(...)`

2023-08-09 16:42 UTC, cortinico commented on packages/rn-tester/android/app/src/main/java/com/facebook/react/uiapp/RNTesterReactHostDelegate.kt
> +    get() =
I think all those `get() =` could be removed as well. Could you verify? (applies to all of them)

2023-08-11 14:26 UTC, cortinico approved these changes
Code looks great now @fabiansolheim but you'll have to rebase this and account for the changes that landed in this commit: 01b9b509cfec9b778eeff15c65e06b520539c7f5

2023-08-11 14:26 UTC, cortinico commented
we can import it after you rebased

2023-08-12 13:53 UTC, closed without merging