Convert ColorUtilTest to Kotlin
facebook/react-native pull request #38979
Opened 2023-08-12 16:26 UTC by okwasniewski

## Summary:

Converts ColorUtilTest to kotlin as requested in #38825

## Changelog:

[INTERNAL] [CHANGED] - Convert ColorUtilTest to Kotlin

## Test Plan:

1. Run `./gradlew :packages:react-native:ReactAndroid:test`.
2. All tests should pass.

2023-08-15 14:18 UTC, cortinico requested changes
Thanks for sending this over @okwasniewski!
Can I ask you to follow-up on my comments and then we can import/merge this

2023-08-15 14:18 UTC, cortinico commented on packages/react-native/ReactAndroid/src/test/java/com/facebook/react/views/view/ColorUtilTest.kt
> +import org.powermock.modules.junit4.rule.PowerMockRule
```suggestion
```

2023-08-15 14:18 UTC, cortinico commented on packages/react-native/ReactAndroid/src/test/java/com/facebook/react/views/view/ColorUtilTest.kt
> +  @get:Rule var rule = PowerMockRule()
```suggestion
```

2023-08-15 14:18 UTC, cortinico commented on packages/react-native/ReactAndroid/src/test/java/com/facebook/react/views/view/ColorUtilTest.kt
> +@PowerMockIgnore("org.mockito.*", "org.robolectric.*", "androidx.*", "android.*")
```suggestion
```

2023-08-15 14:18 UTC, cortinico commented on packages/react-native/ReactAndroid/src/test/java/com/facebook/react/views/view/ColorUtilTest.kt
> +    Assert.assertEquals(-0x3fedcbaa, ColorUtil.multiplyColorAlpha(-0x3fedcbaa, 255).toLong())
Can we avoid using the `-` and retain the old values?

2023-08-15 14:18 UTC, cortinico commented on packages/react-native/ReactAndroid/src/test/java/com/facebook/react/views/view/ColorUtilTest.kt
> +      ColorUtil.getOpacityFromColor(-0x40000000).toLong()
same as above

2023-08-15 14:18 UTC, cortinico commented on packages/react-native/ReactAndroid/src/test/java/com/facebook/react/views/view/ColorUtilTest.kt
> +    Assert.assertEquals(-0x7ff4e9df, ColorUtil.normalize(11.0, 22.0, 33.0, 0.5).toLong())
same as above

2023-08-22 07:21 UTC, okwasniewski commented
Hey @cortinico thanks for the review. I've applied your suggestions.

2023-08-22 09:16 UTC, cortinico commented
Converted to draft, please move it back once it's ready for review.


The tests that are failing are:
```
com.facebook.react.views.view.ColorUtilTest > testNormalize FAILED
    junit.framework.AssertionFailedError at ColorUtilTest.kt:43

com.facebook.react.views.view.ColorUtilTest > testMultiplyColorAlpha FAILED
    junit.framework.AssertionFailedError at ColorUtilTest.kt:24
```

2023-08-27 09:10 UTC, okwasniewski commented
@cortinico Tests are now passing - ready for rereview

2023-08-29 20:45 UTC, mdvacca approved these changes
lgtm

2023-09-04 11:33 UTC, closed without merging