Migrated UIManagerModuleConstantsTest.java to UIManagerModuleConstant…
facebook/react-native pull request #38994
Opened 2023-08-14 16:44 UTC by giolaq

## Summary:

This PR converts UIManagerModuleConstantsTest.java into Kotlin as requested in [https://github.com/facebook/react-native/issues/38825](https://github.com/facebook/react-native/issues/38825)

## Changelog:

[INTERNAL] [CHANGED] - Convert to UIManagerModuleConstantsTest.java to UIManagerModuleConstantsText.kt

## Test Plan:

```./gradlew :packages:react-native:ReactAndroid:test``` must pass and CI must be green

<img width="1297" alt="Screenshot 2023-08-14 at 17 43 14" src="https://github.com/facebook/react-native/assets/2865799/13a9c2b0-3f47-48da-b663-87e2cb652c69">

2023-08-14 17:46 UTC, giolaq commented
PR is ready for review @cortinico @mdvacca. 3 circleci have unexpected errors that should not be related to code

2023-08-15 13:00 UTC, cortinico requested changes
Thanks for taking the time to sending this over @giolaq 🙏 
You will have to rebase + apply the suggestions I recommended before we can merge this one.

2023-08-15 13:00 UTC, cortinico commented on packages/react-native/ReactAndroid/src/test/java/com/facebook/react/uimanager/UIManagerModuleConstantsTest.kt
> +  @get:Rule var rule = PowerMockRule()
```suggestion
```

2023-08-15 13:00 UTC, cortinico commented on packages/react-native/ReactAndroid/src/test/java/com/facebook/react/uimanager/UIManagerModuleConstantsTest.kt
> +  private class ConcreteViewManager(val viewName: String) : SimpleViewManager<View?>() {
```suggestion
  private class ConcreteViewManager(val viewName: String) : SimpleViewManager<View>() {
```

2023-08-15 13:00 UTC, cortinico commented on packages/react-native/ReactAndroid/src/test/java/com/facebook/react/uimanager/UIManagerModuleConstantsTest.kt
> +    }
```suggestion
    override fun createViewInstance(reactContext: ThemedReactContext): View = View(reactContext)
```

2023-08-15 13:00 UTC, cortinico commented on packages/react-native/ReactAndroid/src/test/java/com/facebook/react/uimanager/UIManagerModuleConstantsTest.kt
> +      constants: MutableMap<String, Map<String, Any>?>
```suggestion
      constants: MutableMap<String, Map<String, Any>>
```

2023-08-15 13:00 UTC, cortinico commented on packages/react-native/ReactAndroid/src/test/java/com/facebook/react/uimanager/UIManagerModuleConstantsTest.kt
> +    }
```suggestion
    override fun getName(): String = viewName
```

2023-08-15 13:00 UTC, cortinico commented on packages/react-native/ReactAndroid/src/test/java/com/facebook/react/uimanager/UIManagerModuleConstantsTest.kt
> +    private fun valueAtPath(nestedMap: Map<String, Any>?, vararg keyPath: String): Any? {
```suggestion
    private fun valueAtPath(nestedMap: Map<String, Any>, vararg keyPath: String): Any? {
```

2023-08-15 13:00 UTC, cortinico commented on packages/react-native/ReactAndroid/src/test/java/com/facebook/react/uimanager/UIManagerModuleConstantsTest.kt
> +        Assertions.assertThat(nestedMap).containsKey(key)
```suggestion
        Assertions.assertThat(key in nestedMap)...
```

2023-08-16 09:02 UTC, cortinico approved these changes
LGTM 👍

2023-08-16 19:21 UTC, closed without merging