【iOS】Fixes ellipsis carries background from trimmed text
facebook/react-native pull request #39408
Opened 2023-09-12 10:33 UTC by zhongwuzw

## Summary:

Fixes #37926. 

## Changelog:

[IOS] [FIXED] - Fixes ellipsis carries background from trimmed text

## Test Plan:

Demo code: 
``` 
<Text numberOfLines={1} ellipsizeMode={'tail'}>Long text <Text style={{backgroundColor: 'red'}}>Nested text</Text></Text>
```

Before fix: 
![image](https://github.com/facebook/react-native/assets/5061845/05467128-a4f9-4f81-bb22-c1085a3bc721)

After fix:
![image](https://github.com/facebook/react-native/assets/5061845/b6b024ae-5329-47d3-a07c-1ba089802edd)

2023-09-12 10:58 UTC, javache commented
I don't think we want to mutate `_textStorage` in the draw path. Would it be possible to do so in the layout path? Also, could you verify this behaviour in the new architecture too?

2023-09-12 11:27 UTC, zhongwuzw commented
> I don't think we want to mutate `_textStorage` in the draw path. Would it be possible to do so in the layout path? Also, could you verify this behaviour in the new architecture too?

@javache Thanks for the review, I have no idea how to do it in the layout path, my thought is we can mutate the textStorage before drawing and restore the textStorage which we mutated after drawing. 

And I tested in new arch and it has the same issue.

2023-09-13 14:25 UTC, javache commented
I would look at making this change in [RCTTextShadowView](https://github.com/facebook/react-native/blob/eddefec5f8dc58a1ecf66944e36d8c780fac7064/packages/react-native/Libraries/Text/Text/RCTTextShadowView.mm#L203) and [RCTTextLayoutManager](https://github.com/facebook/react-native/blob/eddefec5f8dc58a1ecf66944e36d8c780fac7064/packages/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTTextLayoutManager.mm#L323) (for the new architecture)

2023-10-08 03:29 UTC, zhongwuzw commented
@javache Friendly ping, thank you for any feedback :)

2023-10-09 08:51 UTC, javache requested changes
Please see my previous feedback about moving this logic on the background thread by using RCTTextShadowView/RCTTextLayoutManager. Please also ensure this is compatible with the new architecture.

2023-10-17 06:23 UTC, zhongwuzw commented on packages/react-native/ReactCommon/react/renderer/components/text/ParagraphLayoutManager.cpp
> +        hostTextStorage_);
Seems Fabric uses different `textStorage`  in measure and draw path. We should share it.

2024-05-10 09:16 UTC, zhongwuzw commented
@javache Seems we can't put it into background thread In new arch, because we use separate textstorage for measure and draw path, because shared of textstorage was removed in https://github.com/facebook/react-native/pull/43914.

2024-07-09 03:25 UTC, zhongwuzw commented
any one can help to review? cc. @sammy-SC @javache

2024-07-09 09:44 UTC, javache commented
Thanks for investigating this. The changes look reasonable, but can we add gating here so we only execute this if numberOfLines is set?

2024-07-09 10:40 UTC, zhongwuzw commented
@javache Done :)

2024-07-09 13:06 UTC, cipolleschi commented
Hi @zhongwuzw, I know that you are fixing a specific issue, but there could be other style properties that we want to remove from the ellipsis.

I think that the ellispis should keep the same style of the character that precedes it, not to have weird artifacts on the screen.
what do you think?

2024-07-10 09:07 UTC, zhongwuzw commented
@cipolleschi Hi, I just keep the same color related attributes as the character that precedes it. Other attributes like fontSize would impact the layout of the text.

2024-07-10 12:30 UTC, javache commented
This is failing internal builds with 

```
packages/react-native/Libraries/Text/Text/RCTTextShadowView.mm:262:64: error: declaration shadows a local variable [-Werror,-Wshadow]
                                     NSTextContainer *_Nonnull textContainer,
```

2024-07-10 13:42 UTC, zhongwuzw commented
@javache done 😀

2024-07-11 15:49 UTC, closed without merging