chore: fix typo / grammar in Xcode 15 helper method names
facebook/react-native pull request #39658
Opened 2023-09-26 13:56 UTC by mikehardy

## Summary:

Thanks for working through Xcode 15 compatibility issues!

I reviewed the diff of the PR that altered Xcode 15 settings for react-native release 0.72.5 and I noticed that

- everything looked great (worth saying)
- there was a typo in one of the new method names, and a grammatical error in another of the method names

Both of those are trivial errors but, as long as I was in there, thought I'd submit a PR

## Changelog:

[IOS] [FIXED] - fix typo / grammar in Xcode 15 helper method names

## Test Plan:

CI should catch it of course, but in general I did a full grep for the names and changed everything / typical method name refactor

2023-09-26 15:30 UTC, cipolleschi requested changes
Hi @mikehardy, thanks for this pr. One of the grammar issue has been fixed already!
Can you rebase the PR on top of main, so we only have the other fix?

2023-09-27 12:32 UTC, cipolleschi approved these changes

2023-09-27 12:34 UTC, mikehardy commented
> Hi @mikehardy, thanks for this pr. One of the grammar issue has been fixed already! Can you rebase the PR on top of main, so we only have the other fix?

Sure thing! rebased to current main as of this typing - edited the commit message to just mention the grammar change since typo already fixed

While I have your attention did you notice that the Xcode 15 linker project file changes are an "always add it" type of thing and thus accumulating on every run? That is every time I run `pod install` now it appears to add a new one, so the `pbxproj` is always perturbed with an extra set of linker commands instead of a "check and only add if not present" type pbxproj change

I'll look for an issue or report it but you may have seen this already. Luckily doesn't seem to effect the actual build (I tested it - if you have multiple instances of the same linker commands it is apparently okay even if untidy)

2023-09-27 13:18 UTC, cipolleschi commented
> While I have your attention did you notice that the Xcode 15 linker project file changes are an "always add it" type of thing and thus accumulating on every run? That is every time I run pod install now it appears to add a new one, so the pbxproj is always perturbed with an extra set of linker commands instead of a "check and only add if not present" type pbxproj change

Yeah, people reported that but I'm struggling to understand why...
We call [this function](https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/cocoapods/utils.rb#L166), implemented [here](https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/cocoapods/utils.rb#L342-L347), to add the flags only if they are missing.

So, unless I forgot how to read, it should add the flags only if it is not included already in the list of flags... 😕

2023-09-27 14:26 UTC, mikehardy commented
> > While I have your attention did you notice that the Xcode 15 linker project file changes are an "always add it" type of thing and thus accumulating on every run? That is every time I run pod install now it appears to add a new one, so the pbxproj is always perturbed with an extra set of linker commands instead of a "check and only add if not present" type pbxproj change
> 
> Yeah, people reported that but I'm struggling to understand why... We call [this function](https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/cocoapods/utils.rb#L166), implemented [here](https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/cocoapods/utils.rb#L342-L347), to add the flags only if they are missing.
> 
> So, unless I forgot how to read, it should add the flags only if it is not included already in the list of flags... 😕
> 
> Anyway, I have an alternative implementation in mind that might be more robust.

I wonder if it is that they are slightly different? Note multi-line flags vs single line, as I take the state of the pbxproj from one invocation of pod install to two

```
mike@win-osxvm2:~/work/invertase/react-native-firebase (@mikehardy/dependency-updates *) % git diff tests/ios/testing.xcodeproj/
diff --git a/tests/ios/testing.xcodeproj/project.pbxproj b/tests/ios/testing.xcodeproj/project.pbxproj
index 10df3dc46..d93855942 100644
--- a/tests/ios/testing.xcodeproj/project.pbxproj
+++ b/tests/ios/testing.xcodeproj/project.pbxproj
@@ -517,6 +517,7 @@
                                        "-Wl",
                                        "-ld_classic",
                                        " ",
+                                       "-Wl -ld_classic ",
                                );
                                REACT_NATIVE_PATH = "${PODS_ROOT}/../../node_modules/react-native";
                                SDKROOT = iphoneos;
@@ -592,6 +593,7 @@
                                        "-Wl",
                                        "-ld_classic",
                                        " ",
+                                       "-Wl -ld_classic ",
                                );
                                REACT_NATIVE_PATH = "${PODS_ROOT}/../../node_modules/react-native";
                                SDKROOT = iphoneos;
mike@win-osxvm2:~/work/invertase/react-native-firebase (@mikehardy/dependency-updates *) % 
```

After that second run, I ran it a third time and received no extra diff. So perhaps it is idempotent after the second run?

Sorry to hijack this totally unrelated thread but I thought I could provide useful info since I reproduce it and have it open on my digital workbench right now

2023-09-27 21:54 UTC, closed without merging