Fix `build_codegen!` not finding `@react-native/codegen` in pnpm setups
facebook/react-native pull request #41399
Opened 2023-11-09 19:33 UTC by tido64

## Summary:

`build_codegen!` currently assumes that `@react-native/codegen` gets installed next to `react-native`. In a pnpm setup, it's found under `/~/react-native/node_modules/@react-native/codegen` instead.

I didn't want to implement Node module resolution in Ruby, so I added yet another path to test. Let me know if you prefer it in a different way.

## Changelog:

[GENERAL] [FIXED] - Fixed `build_codegen!` not finding `@react-native/codegen` in pnpm setups

## Test Plan:

We have a patched version of `react-native` working in a pnpm setup here: https://github.com/microsoft/rnx-kit/pull/2811

2023-11-10 12:20 UTC, cipolleschi commented
The changes are fine to me, but I'm a bit worried about its scalability in other setups. Also, we already have kind-of a node resolution in ruby [here](https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L32-L36).
WDYT about reusing this approach and cleanup those three paths to a single one?

2023-11-10 13:37 UTC, cipolleschi commented
Wow, they are just 3 or 4 functions of 3/4 lines each! 
I think it would be great to have them in Core, tbh!

2023-11-10 14:36 UTC, cipolleschi approved these changes

2023-11-10 15:17 UTC, dmytrorykun requested changes
@tido64  Could you please clarify the use case?
If I understand the purpose of this function correctly, it is only supposed to be used when we are working from within react-native monorepo, and consuming codegen package form source, form `packages/react-native-codegen`.
And in that case it is sufficient to run the build only inside `packages/react-native-codegen`,  and then it will be symlinked to any location the package manager decides.
So I'd suggest to try to delete all the code, but the part that runs the build inside `packages/react-native-codegen`, and it should just work.

2023-11-10 15:37 UTC, tido64 commented
> @tido64  Could you please clarify the use case?

We have a repo with pnpm setup. If I run `pod install` in this repo, it fails. I'm just trying to fix the failure. We don't use this script directly.

2023-11-10 15:53 UTC, dmytrorykun commented
@tido64 I assume in that case codegen is downloaded from NPM, and we shouldn't be trying to build it. I think the proper fix for this issue should be not trying to build it anywhere but in `packages/react-native-codegen`. Something like:
```
def build_codegen!(react_native_path, relative_installation_root, dir_manager: Dir)
  codegen_repo_path = "#{basePath(react_native_path, relative_installation_root)}/../react-native-codegen";
  if dir_manager.exist?(codegen_repo_path) && !dir_manager.exist?("#{codegen_repo_path}/lib")
    Pod::UI.puts "[Codegen] building #{codegen_repo_path}."
    system("#{codegen_repo_path}/scripts/oss/build.sh")
  end
end
```

2023-11-13 10:42 UTC, dmytrorykun approved these changes
Amazing, thank you!

2023-11-13 10:43 UTC, tido64 commented
> Amazing, thank you!

Thanks for pointing out the fact that we don't need to build it. I thought it was a bit weird, but didn't give it a second thought.

2023-11-13 16:03 UTC, closed without merging