fix(metro-config): emit typescript declarations for `@react-native/metro-config`
facebook/react-native pull request #41836
Opened 2023-12-07 14:17 UTC by byCedric

## Summary:

This adds `@react-native/metro-config` to the monorepo build tool and emits the missing typescript declarations.

Right now, we do have typescript declarations on `metro-config`, but not `@react-native/metro-config`. Which makes everything a bit harder for integration in Expo.

> Note, I also added the same `exports` block from `@react-native/dev-middleware` for conformity.

## Changelog:

[INTERNAL] [FIXED] - Emit typescript declaration files for `@react-native/metro-config`

## Test Plan:

Run the build tool, and check if the typescript declarations are emitted for `@react-native/metro-config`.

2023-12-07 14:43 UTC, huntie reviewed
Great! I reckoned Expo was providing its own default config package — but perfectly happy to add TypeScript ergonomics :).

I'm just going to make sure this runs in RNTester — believe we may need to add the wrapping `.js`/`.flow.js` pattern to have run-from-source behaviour in this repo / internally at Meta.

2023-12-07 14:50 UTC, byCedric commented
> Great! I reckoned Expo was providing its own default config package — but perfectly happy to add TypeScript ergonomics :).
> 
> I'm just going to make sure this runs in RNTester — believe we may need to add the wrapping `.js`/`.flow.js` pattern to have run-from-source behaviour in this repo / internally at Meta.

We are! But, there are fixes inside this React Native config that aren't backported inside the `metro-config` package. Things such as [these `require.resolve` blocks](https://github.com/facebook/react-native/blob/v0.73.0/packages/metro-config/index.js#L72-L77).

We can fork this in our own `@expo/metro-config`, but it seems that `metro-config` should be properly fixed if we want to do that instead. Or am I missing something? 😄

2023-12-19 14:28 UTC, huntie commented
> One open question here is, why aren't we exporting all helper functions from metro-config? To me, its a bit weird that we need both `metro-config` and `@react-native/metro-config` as `loadConfig` isn't exported.

Ah, just spotted this question. The reasoning here is that only `mergeConfig` is needed inside a consuming `metro.config.js` file, since it returns an object/function that will be loaded by Metro.

`loadConfig` is side-effectful and part of Metro's internals (it's ultimately used to read `metro.config.js` in a project) — it's beyond the scope of the above.

2023-12-19 14:32 UTC, huntie requested changes

2023-12-19 14:32 UTC, huntie commented on packages/metro-config/src/index.flow.js
> + * @flow strict-local
Ah my bad, let's loosen this to `@flow` so that CI passes.

2024-02-12 13:26 UTC, closed without merging