Update `MainActivity.kt` to correctly return placeholder name
facebook/react-native pull request #41930
Opened 2023-12-13 21:21 UTC by szymonrybczak

## Summary:

Related https://github.com/react-native-community/cli/issues/2205

CLI when replacing placeholders in `init` command looks for `return "HelloWorld"`, but during template's conversation from Java to Kotlin this function was simplified, and scripting for editing template doesn't see this anymore. 

## Changelog:

[ANDROID] [FIXED] - Update `MainActivity.kt` to correctly return placeholder name

## Test Plan:

`npx react-native init appname --package-name com.asdf.zxcv` shouldn't replace main component name in `MainActivity.kt`

2023-12-14 13:24 UTC, szymonrybczak commented
cc @cortinico

2023-12-14 17:27 UTC, ryancat commented
This makes sense, but it also shows our CLI failed to support single-expression functions in Kotlin. Might not be too bad as we have control with the template though.

2023-12-15 11:29 UTC, cipolleschi requested changes
Hi @szymonrybczak, thanks for the PR.

I don't think that this is the right fix, tbh.

The way the `MainActivity` has been migrated is the idiomatic way to write Kotlin code. I don't think that we should denaturalize the idiomatic way to write Kotlin due to an external tool. 

I think that the right fix here is to adapt the CLI to handle Kotlin properly, so the CLI should:
- Check for the MainActivity file type.
- If it is `.java`, replace `return "HelloWorld"` with `return <AppName>`
- If it is `.kt`, replace `= "HelloWorld"` with `= <AppName>`

2023-12-15 12:27 UTC, szymonrybczak commented
Hey @cipolleschi, alright. I was really wondering if this PR should land here or in CLI. Created: https://github.com/react-native-community/cli/pull/2209

2023-12-15 12:27 UTC, closed without merging

2023-12-15 15:02 UTC, cortinico commented
> I don't think that this is the right fix, tbh.

Agree. Can we instead update the CLI to account for ` = "HelloWorld"` as well?