fix: singletonMap for module events
facebook/react-native pull request #42354
Opened 2024-01-18 10:55 UTC by WoLewicki

## Summary:

Sometimes the events map can be a of type `SingletonMap` which will cause this code to throw exception when adding keys to it, so we change it to normal `HashMap`. Creating `SingletonMap` can especially happen in Kotlin when there is only one event added to a map, see:
https://github.com/plaid/react-native-plaid-link-sdk/blob/5ffab5eef576163528f0da504181162da3bef08b/android/src/main/java/com/plaid/PLKEmbeddedViewManager.kt#L21
## Changelog:

[ANDROID] [FIXED] - Cover SingletonMap when parsing events exported by module

## Test Plan:

Create `getExportedCustomBubblingEventTypeConstants` as `SingletonMap` in some example module and see that the code does not throw.

2024-01-18 11:11 UTC, javache requested changes
Checking for string names of types is not the right solution. Can we improve the types here, so when exported to Kotlin it becomes clearer this needs to be a mutable map?

2024-01-18 11:13 UTC, javache commented on packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIManagerModuleConstantsHelper.java
> +    }
Consider the logic done below 
```suggestion
    if (!(events instanceof HashMap)) {
      events = new HashMap(events);
    }
```

2024-01-18 11:29 UTC, WoLewicki commented
Do you want another PR where we change the type to `HashMap` everywhere for this method? Would it be viewed as a breaking change?

2024-01-18 11:29 UTC, WoLewicki commented on packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIManagerModuleConstantsHelper.java
> +    }
done

2024-06-11 16:18 UTC, cortinico approved these changes
I think we can go ahead with your workaround @WoLewicki 
In general we should update this class to Kotlin and potentially update `normalizeEventTypes` to return the updated map and not rely on mutability.

2024-06-11 19:23 UTC, closed without merging