🚑 hotfix Flatlist bug Cannot read property 'getItem' of undefined
facebook/react-native pull request #42401
Opened 2024-01-19 18:51 UTC by a-tokyo

fixes the issue https://github.com/facebook/react-native/issues/36828

## Summary:

There's a bug that shows up with RN 0.73 FlatList component `Cannot read property 'getItem' of undefined`

## Changelog:

Attaching the props to the class fixes the issue

Pick one each for the category and type tags:

[GENERAL] [FIXED] - Fix FlatList props setting

For more details, see:
https://reactnative.dev/contributing/changelogs-in-pull-requests
-->

## Test Plan:

2024-01-19 18:54 UTC, NickGerleman requested changes
This is... pretty jank.

It sounds like the root cause of this issue is a combination of Babel plugins which leads to invalid generated code.

IIRC there has been work so that default babel configuration in new RN supports private class fields out of the box, but I am not certain if this landed in 0.73.

2024-01-19 19:06 UTC, a-tokyo commented
@NickGerleman I agree tbh -- From my end I was able to solve it by adjusting custom babel modules -- but it seems a lot of issues on the web are revolving around this atm -- I'd hope for a better fix in 0.73.3

2024-01-19 20:59 UTC, NickGerleman commented
I confirmed that 0.73 should support private methods and properties out of the box (with https://github.com/facebook/react-native/commit/db4a253c1e8bad29df83cb649cef4132701930f0)

2024-01-21 23:15 UTC, joe-sam commented
Is there any way to git bisect and revert the commit that introduced this behaviour ? 

_this.props_ should be available in the constructor automatically after calling _super(props)_ 
Having to invoke this manually seems like a terribly unfortunate workaround. But thanks for highlighting the issue !

2024-01-21 23:39 UTC, closed without merging

2024-01-21 23:39 UTC, NickGerleman commented
@joe-sam this is a sign your project has customized your babel configuration to an invalid state.

This issue does not happen with the out of the box Babel transform we distribute.

The RN team is not going to accept this fix, since it's not possible to reason about external Babel configs which corrupt code in ways we don't expect.