[iOS] Fixes root view's background color in bridgeless mode
facebook/react-native pull request #42739
Opened 2024-01-30 15:31 UTC by zhongwuzw

## Summary:
Fixes root view's background color in bridgeless mode, the top area has white background color when in dark mode.

Before:
![Simulator Screenshot - iPhone 15 - 2024-01-30 at 23 28 48](https://github.com/facebook/react-native/assets/5061845/4359385d-370d-48cf-a58e-e2e9eb871400)

After:
![Simulator Screenshot - iPhone 15 - 2024-01-30 at 23 25 39](https://github.com/facebook/react-native/assets/5061845/5e9d2029-43d2-40c3-b2cb-c8a9ee80a5e1)

## Changelog:

[IOS] [FIXED] - [iOS] Fixes the root view's background color in bridgeless mode

## Test Plan:

Run RNTester and see the top area's background color.

2024-01-30 20:34 UTC, javache commented
This doesn't seem like the right location for the fix. I'd imagine that the rootview actually covers the entire screen, and that the RNTester root should set the background color on the outmost container view, instead of something that's inside the SafeAreaView.

2024-01-30 20:36 UTC, javache requested changes
Fix should be on the JS side.

2024-01-31 01:45 UTC, zhongwuzw commented
@javache Emm, it's the default color for the root view, actually we do the same thing in non-bridgeless mode, please see:
```
- (UIView *)createRootViewWithBridge:(RCTBridge *)bridge
                          moduleName:(NSString *)moduleName
                           initProps:(NSDictionary *)initProps
{
  [self _logWarnIfCreateRootViewWithBridgeIsOverridden];
  BOOL enableFabric = self.fabricEnabled;
  UIView *rootView = RCTAppSetupDefaultRootView(bridge, moduleName, initProps, enableFabric);

  rootView.backgroundColor = [UIColor systemBackgroundColor];

  return rootView;
}
```
https://github.com/facebook/react-native/blob/25c5d1c341d746e8572d9e1a727cd4517b5b1e80/packages/react-native/Libraries/AppDelegate/RCTAppDelegate.mm#L169

2024-01-31 10:39 UTC, javache approved these changes
Ah, thanks for pointing that out. Still not a big fan for this, but let's do it for consistency.

2024-01-31 11:32 UTC, closed without merging