Remove unused `isPressable` text attribute
facebook/react-native pull request #42969
Opened 2024-02-12 16:17 UTC by cubuspl42

## Summary:

Remove unused `isPressable` text attribute

## Changelog:

[INTERNAL] [REMOVED] - Remove unused `isPressable` text attribute

## Test Plan:

2024-02-12 16:18 UTC, cubuspl42 commented
I assume that if this builds, it works.

2024-02-16 05:16 UTC, NickGerleman requested changes
I can see how it is confusing that these props/attributes aren't used anywhere in this repo. Before removing code as unused, it's usually a good idea to look back at source history. In this case, @rozele actually added these pretty recently, for the windows implementation of RN (outside of this repo).

<img width="400" alt="image" src="https://github.com/facebook/react-native/assets/835219/8d68d1d5-8d59-4319-bfbc-c221cb6d4d2d">

2024-02-16 09:07 UTC, cubuspl42 commented
Sorry, my bad. But yeah, it's confusing why those implementations are kept in separate repositories if the core is aware of them on such low level.

2024-02-16 09:07 UTC, closed without merging

2024-02-16 09:24 UTC, cubuspl42 commented
If I were to change the structure of `AttributedString`, would I also be responsible for updating the external React Native implementations? What's the dynamic here?

Also, how many implementations are there, besides Windows and Skia?