Remove RCTBridgeWillInvalidateModulesNotificationobserver from RCTDeviceInfo
facebook/react-native pull request #45012
Opened 2024-06-17 17:56 UTC by hromovp

## Summary:

I noticed that after application reload useWindowDimensions stops listening to dimension changes on app orientation change, width and height had always the same value regardles of orientation.
On further investigation it became clear that invalidating method were running twice on turndown, which led me to believe that turbomodule already invalidating imperatively (as stated in the comment by author of workaround) and calling notification handler invalidates newly created module, as a result nothing handles screen size changes.

Also I removed codesigning for running tests as it request development team.

## Changelog:

- Removed workaround for invalidating RCTDeviceInfo module;
- Removed codesigning for tests;

Pick one each for the category and type tags:

[IOS] [REMOVED] - Message

2024-06-18 10:29 UTC, cipolleschi requested changes
Hi @hromovp, thanks for the contribution.
I don't think we can proceed with this, given that we needed to listen to that event to make sure that `RCTDeviceInfo` is invalidated.

Calling the event twice, in the tear-down step should be idempotent, so it should not cause any issue. 

Out of curiosity: which configuration are you using?
Are you on the new architecture? Are you using bridgeless or not?

2024-06-18 10:29 UTC, cipolleschi commented on scripts/objc-test.sh
> -      "${SKIPPED_TESTS[@]}"
Can you do this in a separate PR, please?

2024-06-18 10:29 UTC, cipolleschi commented on packages/react-native/React/CoreModules/RCTDeviceInfo.mm
> -                                               name:RCTBridgeWillInvalidateModulesNotification
We can't really remove this. 
If you look at the change that introduced this, it solves another bug: https://github.com/facebook/react-native/issues/42120.

2024-06-18 10:30 UTC, cipolleschi commented on packages/react-native/React/CoreModules/RCTDeviceInfo.mm
> -                                               name:RCTBridgeWillInvalidateModulesNotification
Also, the PR that introduced this is https://github.com/facebook/react-native/commit/d46d80d2ef6cdc05c5a1b2429ed1df93410ae36f and a further fix later in https://github.com/facebook/react-native/commit/91279a822be949051866a694148e509c1308035b

2024-06-19 17:54 UTC, hromovp commented
Hi @cipolleschi, I am using 0.74.2 with bridge. 
The problem with this is that notification's center notification arriving after the teardown already happened and new instance was initialized, so its invalidating newly created instance. It happends for me when I trigger `RCTTriggerReloadCommandListeners`

I am fully aware of the issue this was resolving and therefore I have only removed notification that is, to my understanding, redundant.

Despite that, I understand your position and tbh main reason for creating this PR was to notify RN team that there could be issue with this. 
I will take my time to submit PR for tests later this week. 
Thank you for review!

2024-06-24 11:48 UTC, cipolleschi commented
The New Architecture with Bridge is not the suggested setup anymore, and we will probably not want to fix it.

If this problem is happening in the Old Architecture, then we need to look into it.

Which one of the two scenarios are you into?

2025-07-09 12:56 UTC, closed without merging