fix: align timer functions' error handling with web standards
facebook/react-native pull request #45092
Opened 2024-06-20 23:14 UTC by thejamesgore

Summary:
Fixes issue [#45085](https://github.com/facebook/react-native/issues/45085) by aligning the error handling of setTimeout, clearTimeout, setInterval, and clearInterval functions in React Native with current web standards. This includes throwing a TypeError for invalid callbacks and ensuring clearTimeout and clearInterval fail silently for invalid IDs. Tests have been added to verify the changes.

Changelog:
[GENERAL] [FIXED] - Align timer functions' error handling with web standards.

Test Plan:
Run yarn test to execute the test suite.
Verify all tests pass, including the newly added tests for setTimeout, clearTimeout, setInterval, and clearInterval by running yarn jest packages/react-native/Libraries/Core/Timers/__tests__/JSTimers-test.js from terminal.

2024-06-21 09:43 UTC, rubennorte commented
Hey @thejamesgore! Thanks a lot for your contribution! Your changes are great, but unfortunately what you're changing is the timers implementation for the current architecture, not for the new one. And in that case, the change is potentially a breaking change because now we're throwing more errors than before.

The changes that are necessary to fix #45085 in the new architecture should be done in `TimerManager.cpp` (yeah, sorry, it's C++).

2024-06-21 10:00 UTC, thejamesgore commented
Hey @rubennorte I shall try again with C++. Should tests to validate be written in ```ReactInstanceTest.cpp``` ?

2024-06-21 10:02 UTC, rubennorte commented
> Hey @rubennorte I shall try again with C++. Should tests to validate be written in `ReactInstanceTest.cpp` ?

Yes, please. We should extract them at some point but don't worry about that for now.

2024-06-24 10:44 UTC, rubennorte requested changes

2024-06-24 10:44 UTC, rubennorte commented on packages/react-native/ReactCommon/react/runtime/TimerManager.cpp
> +                                : jsi::Function::createFromHostFunction(
Creating a host function for invalid calls seems wasteful and I don't think it's necessary. I saw that Chrome returns `0` for some types of calls to `setTimeout` (e.g.: `setTimeout('')`) so we could do that same here (just return `jsi::Value(0)`.

You need to make another change to make that work though. In `TimerManager.h` we initialize the value with `0` (as the initial timer handle) and we should change that to 1, so the first timer doesn't conflict with an "invalid" one. When you do that, might be worth renaming `timerIndex_` as `nextTimerHandle_` for clarity.

This is another aspect where we'll align with the spec: https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#timer-initialisation-steps (the handle must be a value greater than 0, but we can use 0 for the invalid ones).

2024-06-24 10:44 UTC, rubennorte commented on packages/react-native/ReactCommon/react/runtime/TimerManager.cpp
> +            auto delay = (count > 1 && args[1].isNumber()) ? args[1].getNumber() : 0;
We should also check for `delay < 0` and assign 0 in that case as well. You can use `std::max(args[1].getNumber(), 0)` in this same expression :)

2024-06-24 10:44 UTC, rubennorte commented on packages/react-native/ReactCommon/react/runtime/TimerManager.cpp
> +                  rt, "setInterval must be called with a function.");
`setInterval` should behave the same way as `setTimeout`. We shouldn't fail if the value isn't a function but just return early with a `0` handle.

2024-06-24 10:44 UTC, rubennorte commented on packages/react-native/ReactCommon/react/runtime/TimerManager.cpp
> +                (count > 1 && args[1].isNumber()) ? args[1].getNumber() : 0;
Same about delay being greater or equal to zero.

2024-06-24 10:44 UTC, rubennorte commented
Could you also please update the PR description with the latest changes you did?

2024-06-25 10:39 UTC, rubennorte commented
Sorry @thejamesgore I didn't realize someone published a similar PR at the same time and one my colleagues merged that one. I'll try to coordinate better next time (probably using issue assignments properly).

2024-06-25 10:39 UTC, closed without merging