fix: Improve Timers error handling and web compatibility (fixes #45085)
facebook/react-native pull request #45105
Opened 2024-06-21 13:01 UTC by robik

## Summary:

Improve compatibility with web implementations of JS timers.

## Changelog:

[GENERAL] [CHANGED] - Timer functions are now throwing exceptions in less cases and are instead quiet quitting (similar to browsers)
[GENERAL] [CHANGED] - Timer functions `timeout` argument is now coerced to a number

## Test Plan:

Updated RN tester

2024-06-21 14:02 UTC, javache requested changes
Thanks for improving this, a few small tweaks please.

2024-06-21 14:02 UTC, javache commented on packages/react-native/ReactCommon/react/runtime/TimerManager.cpp
> +    auto delayNumericValue = delayNumberObject.getPropertyAsFunction(rt, "valueOf").callWithThis(rt, delayNumberObject, nullptr, 0);
```suggestion
    auto delayNumericValue = delayNumberObject.getPropertyAsFunction(rt, "valueOf").callWithThis(rt, delayNumberObject);
```

2024-06-24 11:49 UTC, robik commented on packages/react-native/ReactCommon/react/runtime/TimerManager.cpp
> +double coerceNumberTimeout(jsi::Runtime& rt, jsi::Value&& timeout) {
Oh, right. This is a leftover, forgot to change this. Good catch!

2024-06-24 15:13 UTC, javache approved these changes

2024-06-24 15:13 UTC, javache commented on packages/react-native/ReactCommon/react/runtime/TimerManager.cpp
> +            auto delay = count > 1 ? coerceNumberTimeout(rt, jsi::Value { rt, args[1] }) : 0.0;
There should be no need to create a new jsi::Value here
```suggestion
            auto delay = count > 1 ? coerceNumberTimeout(rt, args[1]) : 0.0;
```

2024-06-24 18:31 UTC, closed without merging