resolve absolute path of the script phase
facebook/react-native pull request #45208
Opened 2024-06-27 15:35 UTC by imWildCat

## Summary:

Since 0.75-rc.x, I cannot run pod install because of an linking issue of react native firebase.

https://github.com/reactwg/react-native-releases/issues/341#issuecomment-2194568204

## Changelog:

[IOS][FIXED] Auto linking script of script phase

For more details, see:
https://reactnative.dev/contributing/changelogs-in-pull-requests
-->

## Test Plan:

Full demo of this fix: <https://github.com/imWildCat-archived/react-native-075-rc2-regression-ios-linking-script-phase>

2024-06-27 15:44 UTC, cipolleschi requested changes
Hi @imWildCat, thanks for taking a stab at this and to create reproducers.
Tampering with the `scriptPhases` is not a good solution, it feels more like a patch.

Let's see if we can find a better solutions first!

2024-06-27 15:49 UTC, imWildCat commented
> Hi @imWildCat, thanks for taking a stab at this and to create reproducers. Tampering with the `scriptPhases` is not a good solution, it feels more like a patch.
> 
> Let's see if we can find a better solutions first!

yeah, sure!

2024-06-27 16:29 UTC, blakef commented
You're super close to the solution.  [This line](https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/cocoapods/autolinking.rb#L171) needs adjusting:

```diff
iff --git a/packages/react-native/scripts/cocoapods/autolinking.rb b/packages/react-native/scripts/cocoapods/autolinking.rb
index fec826c541e..9508625fc4c 100644
--- a/packages/react-native/scripts/cocoapods/autolinking.rb
+++ b/packages/react-native/scripts/cocoapods/autolinking.rb
@@ -168,7 +168,7 @@ def link_native_modules!(config)

         # Support passing in a path relative to the root of the package
         if phase["path"]
-          phase["script"] = File.read(File.expand_path(phase["path"], package["root"]))
+          phase["script"] = File.read(File.expand_path(phase["path"], package[:root]))
           phase.delete("path")
         end
```

Do you want to update your diff?

2024-06-27 17:04 UTC, imWildCat commented
@blakef done. thank you so much!

2024-06-27 17:08 UTC, imWildCat commented
Update: I did some test runs on my repro repo

This does not seem to work:

```diff
diff --git a/before.txt b/after.txt
index fec826c..9508625 100644
--- a/before.txt
+++ b/after.txt
@@ -168,7 +168,7 @@ def link_native_modules!(config)
 
         # Support passing in a path relative to the root of the package
         if phase["path"]
-          phase["script"] = File.read(File.expand_path(phase["path"], package["root"]))
+          phase["script"] = File.read(File.expand_path(phase["path"], package[:root]))
           phase.delete("path")
         end
 ```

```
ios git:(main) pod install --repo-update
RNFBAnalytics: Using default Firebase/Analytics with Ad Ids. May require App Tracking Transparency. Not allowed for Kids apps.
RNFBAnalytics: You may set variable `$RNFirebaseAnalyticsWithoutAdIdSupport=true` in Podfile to use analytics without ad ids.
Found 3 modules for target `AwesomeProject7`
link_native_modules! {:ios_packages=>[{:configurations=>[], :name=>"@react-native-firebase/analytics", :path=>"../node_modules/@react-native-firebase/analytics", :podspec_path=>"/Volumes/QuickMac/temp/202406/AwesomeProject7/node_modules/@react-native-firebase/analytics/RNFBAnalytics.podspec", :script_phases=>[]}, {:configurations=>[], :name=>"@react-native-firebase/app", :path=>"../node_modules/@react-native-firebase/app", :podspec_path=>"/Volumes/QuickMac/temp/202406/AwesomeProject7/node_modules/@react-native-firebase/app/RNFBApp.podspec", :script_phases=>[{"name"=>"[RNFB] Core Configuration", "path"=>"./ios_config.sh", "execution_position"=>"after_compile", "input_files"=>["$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)"]}]}, {:configurations=>[], :name=>"react-native-svg", :path=>"../node_modules/react-native-svg", :podspec_path=>"/Volumes/QuickMac/temp/202406/AwesomeProject7/node_modules/react-native-svg/RNSVG.podspec", :script_phases=>[]}], :ios_project_root_path=>"/Volumes/QuickMac/temp/202406/AwesomeProject7/ios", :react_native_path=>"../node_modules/react-native"}
RNFBAnalytics: Using default Firebase/Analytics with Ad Ids. May require App Tracking Transparency. Not allowed for Kids apps.
RNFBAnalytics: You may set variable `$RNFirebaseAnalyticsWithoutAdIdSupport=true` in Podfile to use analytics without ad ids.
Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration

[!] Invalid `Podfile` file: No such file or directory @ rb_sysopen - /Volumes/QuickMac/temp/202406/AwesomeProject7/ios/ios_config.sh.

 #  from /Volumes/QuickMac/temp/202406/AwesomeProject7/ios/Podfile:18
 #  -------------------------------------------
 #  target 'AwesomeProject7' do
 >    config = use_native_modules!
 #  
 #  -------------------------------------------
```

2024-06-27 17:11 UTC, cipolleschi commented
Yup, I was testing the same.
The right fix is not `:root` but `:path`.

This works:
```diff
if phase["path"]
-  phase["script"] = File.read(File.expand_path(phase["path"], package[:root]))
+  phase["script"] = File.read(File.expand_path(phase["path"], package[:path]))
  phase.delete("path")
end
```

2024-06-27 17:12 UTC, cipolleschi commented
sorry for the back and forth

2024-06-27 17:23 UTC, imWildCat commented
no worries at all! thanks!

https://github.com/imWildCat-archived/react-native-075-rc2-regression-ios-linking-script-phase/actions/runs/9700897360/job/26773347289

test run (I believe it will be green)

2024-06-27 23:18 UTC, closed without merging

2024-06-28 10:05 UTC, cipolleschi commented
committed @ e320ab47cf855f2e5de74ea448ec292cf0bbb29a

2024-06-28 16:25 UTC, mikehardy commented
@imWildCat thank you so much for spotting this and *more importantly* the PR with fix 🎉

2024-06-28 16:53 UTC, imWildCat commented
> @imWildCat thank you so much for spotting this and _more importantly_ the PR with fix 🎉

My pleasure! 

Thanks a lot to the maintainers for the suggestions and prompt review!