fix: iOS crash occurring when navigating to a new app screen with a displaying modal
facebook/react-native pull request #45313
Opened 2024-07-08 11:32 UTC by zhouzh1

## Summary:

Our app is using the react-native v0.74.2 with the `react-navigation` lib for screen navigation, we're facing an issue in the built iOS app that when we try to navigate to a new app screen with the `react-navigation`'s `reset` or `replace` method and meanwhile there's a react native modal displaying, then the iOS app always crashes.

I saw there is already a relevant [PR](https://github.com/facebook/react-native/pull/38491) and discussion targeting this issue, but I still think it would be better if this kind of crash can be suppressed in the framework level, currently I guess it's common in the iOS apps based on react native.

## Changelog:

[IOS] [FIXED] - app crash happening when navigate to a new app screen with a displaying modal

## Test Plan:

More issue details and the reproduction steps can be found in this [PR](https://github.com/facebook/react-native/pull/38491) :)

2024-07-08 11:39 UTC, zhouzh1 commented
@mojodna @jsierles @augustl could you help take a review? Thanks.

2024-07-16 07:59 UTC, zhouzh1 commented
Anyone can help take a look or provide some insights about if this change is safe or not?

2024-08-08 23:36 UTC, mrand15 commented
This issue is causing multiple crashes for us in production every day. Would appreciate if a fix like this could be merged. We use reset/replace actions when following deep links. No good way to know if the user has a modal open when we do so.

2024-08-12 07:15 UTC, zhouzh1 commented
@mrand15 Glad to hear that it's working for you, I already applied this fix in our production app for a long while, seems that this issue has been resolved and this change didn't introduce other new issues.
@cortinico Could you help take a look please?

2024-08-13 15:27 UTC, cipolleschi approved these changes
I can see that this is a fix for the old architecture only. Can I ask you to work also on the New Architecture?

The twin file should be this one: [RCTModalHostViewComponentView](https://github.com/facebook/react-native/blob/main/packages/react-native/React/Fabric/Mounting/ComponentViews/Modal/RCTModalHostViewComponentView.mm).

2024-08-13 15:28 UTC, cipolleschi requested changes
Sorry, I misclicked on 'Approve'.
We try not to accept fixes for the Old Architecture only. We would like at least to have the same fix in the New Arch or have a check that the New Arch does not suffer from the same issue.

2024-08-14 06:33 UTC, zhouzh1 commented
@cipolleschi Sorry that our app hasn't started to apply the new React native architecture, so I am not sure if it's suffering from this issue as well, but I took a look at the above [RCTModalHostViewComponentView](https://github.com/facebook/react-native/blob/main/packages/react-native/React/Fabric/Mounting/ComponentViews/Modal/RCTModalHostViewComponentView.mm) file that you posted, I guess it's no problem, because in this file, the ` _shouldPresent` variable replaces the `_visible` variable in the old architecture, and there is already such a process similar to what this fix PR does.

2024-08-19 02:09 UTC, zhouzh1 commented
@cipolleschi Could you help take a look again? We're going to upgrade the react native in our project, if this fix makes sense,  then we may don't need the extra patch file for react native.

2024-08-20 12:26 UTC, cipolleschi approved these changes
thanks for fixing! Which version of React Native are you using?

2024-08-20 17:11 UTC, closed without merging

2024-08-20 17:17 UTC, cipolleschi commented
@zhouzh1 which version are you using? can you create a [pick request](https://github.com/reactwg/react-native-releases/issues/new?assignees=&labels=Type%3A+Pick+Request&projects=&template=pick_request_form.yml&title=%5B0.XX%5D+Title) for the versions that needs the fix?

2024-09-26 05:56 UTC, gkasireddy202 commented
@cipolleschi - My project has upgraded to react-native:0.73.7 3 months back.
Can I add this line  [self setVisible: NO]; below the code for a temporary fix?
We will upgrade my project to the latest react-native version once the client approves the newest version.

- (void)dismissModalViewController
{
  if (_isPresented) {
    [_delegate dismissModalHostView:self withViewController:_modalViewController animated:[self hasAnimationType]];
    _isPresented = NO;

[self setVisible: NO]  // Add this line //
  }
}

2024-09-26 06:34 UTC, gkasireddy202 commented
@cipolleschi  - My project has upgraded to react-native:0.73.7 3 months back.I raised this issue #44612 .
Can I add this line [self setVisible: NO]; below the code for a temporary fix or Can I pick a request to react-native:0.73.7 to fix this issue?
node_modules>react-native>React>Views>RCTModalHostView.m
We will upgrade my project to the latest react-native version once the client approves the newest version.

(void)dismissModalViewController
{
if (_isPresented) {
[_delegate dismissModalHostView:self withViewController:_modalViewController animated:[self hasAnimationType]];
_isPresented = NO;
[self setVisible: NO] // Add this line //
}
}

2024-09-26 13:19 UTC, cipolleschi commented
yeah, 0.73 is still in the support window. 
I created the cherry pick request: https://github.com/reactwg/react-native-releases/issues/531
We need the same pick for other versions too, let me create them.

2024-09-26 13:26 UTC, gkasireddy202 commented
@cipolleschi - Thanks for your update.
https://github.com/reactwg/react-native-releases/issues/531 release fix will resolve my issue #44612 ?

2024-09-26 13:38 UTC, cipolleschi commented
@gkasireddy202 I don't know... I understood you were asking to pick the fix because you tested it and it fixed it... 😅 

Can you try to:
1. add that line in your project 
2. try to trigger the crash
3. report back whether it worked or not

2024-09-26 13:47 UTC, gkasireddy202 commented
@cipolleschi - I added that line to my project and tested it. I triggered the crash.
This is the issue that I faced in react-native:0.73.7.

https://github.com/facebook/react-native/issues/44612#issuecomment-2360716821