fix: onChangeText should be called only once if changed via js in a multiline textinput
facebook/react-native pull request #45401
Opened 2024-07-12 07:31 UTC by deepanshushuklad11

Fixes [44566](https://github.com/facebook/react-native/issues/44566)

## Summary:

Issue was onChangeText was called 5-6 times if maxLength was set in a multiline component and TextInput Value was changed via state update.
`if (_maxLength) {
    NSInteger allowedLength = MAX(
        _maxLength.integerValue - (NSInteger)backedTextInputView.attributedText.string.length + (NSInteger)range.length,
        0);

    if (text.length > allowedLength) {
      // If we typed/pasted more than one character, limit the text inputted.
      if (text.length > 1) {
        if (allowedLength > 0) {
          // make sure unicode characters that are longer than 16 bits (such as emojis) are not cut off
          NSRange cutOffCharacterRange = [text rangeOfComposedCharacterSequenceAtIndex:allowedLength - 1];
          if (cutOffCharacterRange.location + cutOffCharacterRange.length > allowedLength) {
            // the character at the length limit takes more than 16bits, truncation should end at the character before
            allowedLength = cutOffCharacterRange.location;
          }
        }
        // Truncate the input string so the result is exactly maxLength
        NSString *limitedString = [text substringToIndex:allowedLength];
        NSMutableAttributedString *newAttributedText = [backedTextInputView.attributedText mutableCopy];
        // Apply text attributes if original input view doesn't have text.
        if (backedTextInputView.attributedText.length == 0) {
          newAttributedText = [[NSMutableAttributedString alloc]
              initWithString:[self.textAttributes applyTextAttributesToText:limitedString]
                  attributes:self.textAttributes.effectiveTextAttributes];
        } else {
          [newAttributedText replaceCharactersInRange:range withString:limitedString];
        }
        backedTextInputView.attributedText = newAttributedText;
        _predictedText = newAttributedText.string;

        // Collapse selection at end of insert to match normal paste behavior.
        UITextPosition *insertEnd = [backedTextInputView positionFromPosition:backedTextInputView.beginningOfDocument
                                                                       offset:(range.location + allowedLength)];
        [backedTextInputView setSelectedTextRange:[backedTextInputView textRangeFromPosition:insertEnd
                                                                                  toPosition:insertEnd]
                                   notifyDelegate:YES];

        [self textInputDidChange];
      }

      return nil; // Rejecting the change.
    }
  }`
This is the original code snippet.
It was happening because of wrong check of maxLength with text length `if (text.length > allowedLength)` this  should be 
`(text.length > _maxLength.integerValue)`  and `if (allowedLength <= 0)`  we should not change the string and fire `textInputDidChange`

## Changelog:

Fixing maxLength check which was firing onChange multiple times

Pick one each for the category and type tags:

[IOS] [FIXED] 

For more details, see:
https://reactnative.dev/contributing/changelogs-in-pull-requests
-->

## Test Plan:
Tested in Ios
Ran yarn test
<img width="1661" alt="Screenshot 2024-07-12 at 1 00 28 PM" src="https://github.com/user-attachments/assets/fbad94a8-9989-4252-ad7d-e507d4eafd9e">

2024-07-15 10:05 UTC, deepanshushuklad11 commented
@cortinico @cipolleschi Any update on this

2024-07-15 13:00 UTC, cipolleschi requested changes
Hi @deepanshushuklad11, thanks for the fix and sorry for te late reply. I missed the PR on friday.

I see that this is the fix only for the Old Arch. Can you verify whether the problem exists also in the New Arch and fix it there as well?
The component where I'd start looking into is [RCTTextInputComponentView](https://github.com/facebook/react-native/blob/main/packages/react-native/React/Fabric/Mounting/ComponentViews/TextInput/RCTTextInputComponentView.mm).

Thank you so much!

2024-07-17 05:51 UTC, deepanshushuklad11 commented
@cipolleschi Anything else required from my end?

2024-07-18 12:58 UTC, cipolleschi approved these changes

2024-07-18 12:59 UTC, cipolleschi commented
Sorry for the delay! I imported the PR, let's see if the internal CI is happy about it!

2024-07-23 17:05 UTC, deepanshushuklad11 commented
> Sorry for the delay! I imported the PR, let's see if the internal CI is happy about it!

Hey @cipolleschi any update ?

2024-07-30 09:30 UTC, cipolleschi commented
Hi @deepanshushuklad11, sorry for the delay, I have been quite busy the past week. I'll try to get to it this week.

2024-07-31 11:11 UTC, closed without merging