chore: ☂️ Migrate PreparePrefabHeadersTaskTest.kt to AssertJ
facebook/react-native pull request #45808
Opened 2024-07-29 23:46 UTC by omer-ayhan

## Summary:
Issue: https://github.com/facebook/react-native/issues/45596

## Changelog:
[INTERNAL] [CHANGED] - Migrate `PreparePrefabHeadersTaskTest.kt` to AssertJ testing library

## Test Plan:
Run `./gradlew -p packages/gradle-plugin test`

2024-07-29 23:46 UTC, omer-ayhan commented
hello @cortinico 👋 this PR is ready for a review🚀

2024-07-30 09:11 UTC, cortinico reviewed
Please update the assertions to use `assertThat(File()).exists()`

2024-07-30 09:11 UTC, cortinico commented on packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/tasks/internal/PreparePrefabHeadersTaskTest.kt
> +    assertThat(File(outputDir, "sample_library/hello.h").exists()).isTrue()
```suggestion
    assertThat(File(outputDir, "sample_library/hello.h")).exists()
```

2024-07-30 09:11 UTC, cortinico commented on packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/tasks/internal/PreparePrefabHeadersTaskTest.kt
> +    assertThat(File(outputDir, "sample_library/hello.h").exists()).isTrue()
This applies to all the assertions.

2024-07-30 09:11 UTC, cortinico requested changes
See above comments

2024-07-30 19:41 UTC, omer-ayhan commented
changes are done @cortinico

2024-07-31 09:58 UTC, cortinico approved these changes

2024-07-31 11:49 UTC, closed without merging