feat: use newArchEnabled in RCTRootViewFactory
facebook/react-native pull request #46652
Opened 2024-09-26 09:09 UTC by okwasniewski

## Summary:

This PR follows up with the deprecation introduced here: https://github.com/facebook/react-native/pull/46228

The idea is to have new architecture depend on one flag, namely `newArchEnabled`. It exposes additional initializers for RCTRootViewFactory. 

## Changelog:

[IOS] [CHANGED] - Use `newArchEnabled` flag in RCTAppDelegate and RCTRootViewFactory

## Test Plan:

CI Green

2024-09-26 15:32 UTC, cipolleschi requested changes
Sadly, we can't merge this. If we do this, people will not be able to turn off selectively parts of the New Architecture, and we are not ready to remove this possibility just yet.

2024-09-27 08:59 UTC, okwasniewski commented
@cipolleschi  Yeah, I was afraid its too early 😅 Do you think we can deprecate RCTRootViewFactory initializers?

2024-10-02 10:11 UTC, cipolleschi commented
>  Do you think we can deprecate RCTRootViewFactory initializers?

What do you mean? Do you want to move away from some initializers?

2024-10-02 11:08 UTC, cipolleschi commented
Yeah, that seems reasonable to me.

2024-10-04 10:15 UTC, okwasniewski commented
@cipolleschi I've deprecated the initializers

2024-10-10 09:57 UTC, cipolleschi approved these changes

2024-10-10 14:43 UTC, closed without merging