feat(Android): add support for invert colors check on android accessibility
facebook/react-native pull request #47341
Opened 2024-10-31 17:46 UTC by oddlyspaced

## Summary:

This PR provides a fix for the long existing issue of missing check for invert color in accessibility options on Android.
Reference Issue : https://github.com/facebook/react-native/issues/30870

## Changelog:
- Added native module code to check for invert color settings value
- Updated js module to return a proper promise instead of default false for isInvertColorsEnabled()

Pick one each for the category and type tags:

[ANDROID] [FIXED] - Missing isInvertColorsEnabled implementation for Android

For more details, see:
https://reactnative.dev/contributing/changelogs-in-pull-requests
-->

## Test Plan:

Tested on OnePlus 12 with Android 14 and Pixel 6 with Android 15. The try catch exists because in some cases if the switch hasn't been toggled before the android system raises the missing settings exception.

2024-10-31 17:48 UTC, oddlyspaced commented
Hello all, this is my first PR here. If there is something that can be improved please let me know. I've triaged a list of small implementations that are missing on android regarding accessibility and aim to add support for all of them. This is a first for the same.

2024-10-31 17:51 UTC, oddlyspaced commented
I have now signed the CLA 👍

2024-10-31 19:01 UTC, oddlyspaced commented
@cortinico apologies if the tag is unnecessary, but can you let me know if all is well here?

2024-11-01 11:27 UTC, cortinico requested changes
Can we add a test for it inside RNTester?

2024-11-01 11:27 UTC, cortinico commented on packages/react-native/Libraries/Components/AccessibilityInfo/AccessibilityInfo.js
> +      ['invertColorsChanged', 'invertColorDidChanged'],
```suggestion
      ['invertColorsChanged', 'invertColorDidChange'],
```

2024-11-01 11:57 UTC, oddlyspaced commented
Sure 👍🏾 
Will update the PR soon.
Thanks a lot!

2024-11-01 12:16 UTC, oddlyspaced commented
@cortinico done. I've moved the test to common scope. On running jest locally, this test seemed to pass well, however some other tests were failing. 🤔

2024-11-02 14:07 UTC, oddlyspaced commented
fixed an incorrect usage of content resolver ^

2024-11-03 13:31 UTC, oddlyspaced commented
@cortinico sorry for the tag again, please lmk if all is good now 🙏🏾

2024-11-04 13:18 UTC, cortinico approved these changes
LGTM 👍

2024-11-04 16:16 UTC, oddlyspaced commented
Is there anything I need to do to fix the failing linter and test workflows ?

2024-11-04 18:11 UTC, closed without merging