fix:fix the deadlock in EventDispatcherImpl.java
facebook/react-native pull request #48197
Opened 2024-12-10 12:35 UTC by MlxChange

## Summary:

## Changelog:

## Test Plan:

2024-12-13 11:14 UTC, javache commented
> when project fabric global switch is on, bridgeLess switch is off, but the rn page set fabric is false when new RootView.

This is no longer a configuration we support for open-source consumers of React Native. You must use Fabric with Bridgeless in the new architecture.

2024-12-13 11:14 UTC, javache requested changes

2024-12-13 11:14 UTC, javache commented on packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/EventDispatcherImpl.java
> +      mEventsStagingSemaphore.release();
Please add comments in English

2024-12-13 11:14 UTC, javache commented on packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/EventDispatcherImpl.java
> +    new Comparator<Event>() {
Revert changes to whitespace please

2024-12-13 14:39 UTC, MlxChange commented on packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/EventDispatcherImpl.java
> +    new Comparator<Event>() {
it‘s fixed

2024-12-13 14:39 UTC, MlxChange commented on packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/EventDispatcherImpl.java
> +      mEventsStagingSemaphore.release();
done

2024-12-13 14:39 UTC, MlxChange commented
> > 当项目fabric全局开关为on时，bridgeLess开关为off，但是new RootView时rn页面设置fabric为false。
> 
> 我们不再为 React Native 的开源消费者提供此配置。您必须在新架构中将 Fabric 与 Bridgeless 结合使用。

Sorry, my description is not clear enough. It is not just this case. Some engine codes have been modified in our business, but the modified part is limited to UI synchronization. In this case, ANR problems caused by deadlocks often occur. I After observing the issues in the comment area, I found that some users have also encountered these problems, so I wonder if using semaphores instead of locks is a better solution? Finally, please forgive my not very good English, thanks

2024-12-17 11:50 UTC, MlxChange commented
@javache Sorry to bother you, I would like to know if there is any progress on this matter?

2024-12-17 11:59 UTC, javache commented
Sorry for the delay. I don't think we want to merge this change. Running a mix of Fabric and non-Fabric roots is not something we support anymore, and this adds risks to the legacy Paper code paths, which have significantly less internal coverage on.

cc @cipolleschi

2024-12-17 11:59 UTC, closed without merging