react-native\packages\react-native\Libraries\Blob\URL.js Changes
facebook/react-native pull request #48333
Opened 2024-12-19 08:40 UTC by bobbysharma05

### SUMMARY
The URL class was refactored to handle blob URLs more effectively, improving URL construction and parsing. Changes include better error handling in the createObjectURL method and the addition of functions to extract URL components like username, host, and protocol.

Fixes #45030

### Changelog:
[General][Added] - Implement missing methods for URL
- Replaced static URL construction with dynamic initialization using NativeBlobModule.
- Enhanced createObjectURL with better validation and error handling.
- Added methods to extract URL components (username, host, protocol).
- Cleaned up unnecessary code for better readability.

### Test Plan:

- Test createObjectURL with valid and invalid Blob data.
- Verify that URL components (hostname, pathname, etc.) are parsed correctly.
- Test integration with URLSearchParams for query handling.

2024-12-19 10:22 UTC, cipolleschi commented
Hi @bobbysharma05, thanks for working on this.
Could you please add a Summary explaining the changes and a Changelog in the PR, following the suggested structure?

2024-12-19 10:23 UTC, cipolleschi requested changes
Code changes look good to me, but the PR is missing information in the Description.
We can't import without Summary, Changelog and TestPlan

2024-12-19 10:23 UTC, cipolleschi commented
Also, the test_js signal is failing, can you have a look at it?

2024-12-19 10:54 UTC, bobbysharma05 commented
ok sir I will look into it and also add the summary.

2024-12-20 10:19 UTC, bobbysharma05 commented
Sir I am new to the open source. Could you please help me in which part I am getting stuck.

2024-12-20 13:47 UTC, cipolleschi commented
When a new pr is open, we provide a template that has to be filled. For the Changelog, specifically, it has to follow a predefined format, which is described [here](https://github.com/facebook/react-native/blob/main/.github/PULL_REQUEST_TEMPLATE.md?plain=1).

For this pr, it should be something like:
```
[General][Fixed] -  implemented missing methods on URL.js
```

For the failures, you can click on the failed signals in the github UI and read through the logs, looking for the errors (the search function is your friend).

For example, the [linter](https://github.com/facebook/react-native/actions/runs/12427492191/job/34711905764?pr=48333#step:3:421) says that the community-cli-plugin has been built and it should not. If you inspect the changed files, you see that you committed a package.json that should not be committed.

The test_js [says](https://github.com/facebook/react-native/actions/runs/12427492191/job/34711905511?pr=48333#step:3:83) that there is an invalid expression at line 25 of the URL.js file.

Build_android failure is related to the failure for the linter, so it should be fixed by reverting the changes in the `community-cli-plugin/package.json`.

2025-01-06 13:30 UTC, cortinico commented
also related PR: https://github.com/facebook/react-native/pull/48505

2025-01-16 18:07 UTC, cipolleschi requested changes
@bobbysharma05, thanks for the patience waiting for the review.
The code currently does not build, there are some syntax error that needs to be fixed.

2025-01-16 18:07 UTC, cipolleschi commented on packages/react-native/Libraries/Blob/URL.js
> +    BLOB_URL_PREFIX += //${constants.BLOB_URI_HOST}/;
this is not valid JS... I believe you forgot a couple of backticks: <code>`</code>

2025-01-16 18:07 UTC, cipolleschi commented on packages/react-native/Libraries/Blob/URL.js
> +  return /^(?:(?:(?:https?|ftp):)?\/\/)(?:(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z0-9\u00a1-\uffff][a-z0-9\u00a1-\
why did you removed the `*`?

2025-01-16 18:07 UTC, cipolleschi commented on packages/react-native/Libraries/Blob/URL.js
> +    return ${BLOB_URL_PREFIX}${blob.data.blobId}?offset=${blob.data.offset}&size=${blob.size};
missing <code>`</code>. This is not valid JS code

2025-01-16 18:07 UTC, cipolleschi commented on packages/react-native/Libraries/Blob/URL.js
> +          throw new TypeError(Invalid base URL: ${baseUrl});
Backticks <code>`</code> are needed here as well

2025-01-16 18:07 UTC, cipolleschi commented on packages/react-native/Libraries/Blob/URL.js
> +        url = /${url};
Backticks `

2025-01-16 18:07 UTC, cipolleschi commented on packages/react-native/Libraries/Blob/URL.js
> +      this._url = ${baseUrl}${url};
Backticks `

2025-03-12 17:25 UTC, cortinico commented
Closing in favor of https://github.com/facebook/react-native/pull/49955

2025-03-12 17:25 UTC, closed without merging