feat: make reactHost accessible
facebook/react-native pull request #48338
Opened 2024-12-19 10:51 UTC by WoLewicki

## Summary:

On bridgeless mode, `reactHost` is kept in memory even after destroying the `DefaultReactNativeHost` in brownfield scenario. Since it keeps references to the modules, they are not deallocated, and their `initialize` methods are not fired again when creating new instance of `react-native` later. It breaks the behavior of e.g. `react-native-screens`, which wants to listen for mutations and should get new `FabricUIManager`: https://github.com/software-mansion/react-native-screens/blob/20b7e83782cd5f79ddd0d61dadc13eeb4db4b258/android/src/main/java/com/swmansion/rnscreens/ScreensModule.kt#L45.

By making the variable public, we can make it `null` when destroying the RN activity, removing references to everything it kept.

## Changelog:

[ANDROID] [FIXED] - make it possible to set `reactHost` to `null`.

## Test Plan:

It shouldn't change anything since it is just change of visibility in the variable.

2024-12-31 15:31 UTC, cortinico commented
/rebase

2024-12-31 15:32 UTC, cortinico commented
Thanks for sending this over @WoLewicki This sounds like a reasonable approach, but I'd like to have @mdvacca 's opinion on this as well

2025-01-08 07:07 UTC, arushikesarwani94 commented
IIRC for internal apps use-case we were able to make use of `getReactHost().destroy()` to address this scenario without needing an explicit `invalidate(`) in DefaultReactHost

cc: @shwanton

2025-01-08 11:20 UTC, cortinico requested changes

2025-01-08 14:38 UTC, WoLewicki commented on packages/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactNativeHost.java
> +  public abstract void invalidate();
I changed it but I am not sure if the `INSTANCE` is the proper way of getting the instance of kotlin object.

2025-01-08 16:44 UTC, cortinico commented on packages/react-native/ReactAndroid/src/main/java/com/facebook/react/defaults/DefaultReactHost.kt
> +  }
can you instead `override fun clear()`, call `super.clear()` and set the reactHost to null here?

2025-01-08 16:45 UTC, cortinico commented on packages/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactNativeHost.java
> +    DefaultReactHost.INSTANCE.invalidate();
this is probably not needed

2025-01-09 10:16 UTC, WoLewicki commented on packages/react-native/ReactAndroid/src/main/java/com/facebook/react/defaults/DefaultReactHost.kt
> +  }
I am not sure I get it. `DefaultReactHost` does not inherit from `ReactNativeHost` so how can I override `clear` method in it? Or am I messing it up?

2025-01-09 10:35 UTC, cortinico commented on packages/react-native/ReactAndroid/src/main/java/com/facebook/react/defaults/DefaultReactHost.kt
> +  }
@WoLewicki you're right, I misread the class title.

I'd suggest instead we do the following:
- Here make `public fun invalidate()` be `internal`
- Inside DefaultReactNativeHost add the following:

```kotlin
  override fun clear() {
    super.clear()
    DefaultReactHost.invalidate()
  }
```

2025-01-09 11:57 UTC, WoLewicki commented on packages/react-native/ReactAndroid/src/main/java/com/facebook/react/defaults/DefaultReactHost.kt
> +  }
Done

2025-01-14 15:35 UTC, closed without merging

2025-01-14 17:20 UTC, cortinico commented
@WoLewicki sorry this took a bit longer. I've also update the commit message/description to reflect the correct behavior https://github.com/facebook/react-native/commit/07769d4d7eb1d3000210c7a8dafd9a5411694444

2025-01-15 08:58 UTC, WoLewicki commented
Ok thanks