feat: linear gradient transition hint syntax
facebook/react-native pull request #48410
Opened 2024-12-30 06:45 UTC by intergalacticspacehighway

## Summary:
- Adds support for color transition hint syntax in linear gradients. e.g. linear-gradient(red, 20%, green).
- Simplified color stops parsing.
- The `processColorTransitionHint` is put into native code so it can support platform colors.
- Follows CSS [spec](https://drafts.csswg.org/css-images-4/#coloring-gradient-line) (Refer transition hint section) and implementation is referred from [blink engine source](https://github.com/chromium/chromium/blob/a296b1bad6dc1ed9d751b7528f7ca2134227b828/third_party/blink/renderer/core/css/css_gradient_value.cc#L240).

## Changelog:

[GENERAL] [ADDED] - Linear gradient color transition hint syntax support.

## Test Plan:

Added testcase in processBackgroundImage-test.ts and example in LinearGradientExample.js

<img width="500" alt="Screenshot 2024-12-27 at 11 22 15 AM" src="https://github.com/user-attachments/assets/85865a66-5065-4300-bd95-70b0d06242b1" />

## Thoughts
Linear gradient fully supports CSS syntax with percentage value color stop positions and this PR adds transition hint support so can we remove experimental status from it?

`px` support can be done but we'll need to move color stop [fixup algorithm](https://github.com/facebook/react-native/blob/fcf3c8cab7568f583c26aacb398f8e8a61da80eb/packages/react-native/Libraries/StyleSheet/processBackgroundImage.js#L287) from JS to native as we'll need view dimensions to support mixing percentage and `px` values. I guess we can hold that until new CSS parser?

2025-01-02 22:57 UTC, joevilches requested changes

2025-01-02 22:57 UTC, joevilches commented on packages/react-native/Libraries/StyleSheet/processBackgroundImage.js
> +            return [];
I think we can change this to share some code better. Do transition hints have to be percentages? Regardless we are doing a lot of the same things, can you try to get rid of the top level if/else here and share some of this logic?

2025-01-02 22:57 UTC, joevilches commented on packages/react-native/Libraries/StyleSheet/processBackgroundImage.js
> +    color: ColorStopColor,
I would comment in what scenarios we can have a null color, or otherwise change the typing to make that super clear like 
```
$ReadOnlyArray<{
  colorStop | transitionHint
}>
```
I think they are similar enough to just roll with the comment but it should be clear that that syntax is supported

2025-01-02 22:57 UTC, joevilches commented on packages/react-native/ReactCommon/react/renderer/components/view/conversions.h
> +              if (colorIt->second.hasValue()) {
what is the default value of the color in ColorStop? Will we be able to detect that this is a transition hint vs something like the color black?

2025-01-02 22:57 UTC, joevilches commented on packages/react-native/React/Fabric/Utils/RCTLinearGradient.mm
> +      continue;
again, curious if a color like black breaks this? Regardless I feel like it would be more future proof and more obvious if you just changed the color in ColorStop to be a std::optional or such

2025-01-02 22:57 UTC, joevilches commented on packages/react-native/Libraries/StyleSheet/__tests__/processBackgroundImage-test.js
> +  });
can you add some more? Hints that are invalid (> 100%, non percents, multiple in a row, etc). Some longer ones with more stops and more hints just to stress test things a bit, etc. The code has a lot of branching logic due to the complexity of the syntax we are allowing, so I think we should err on the side of excessive testing to raise our confidence level here

2025-01-03 08:43 UTC, intergalacticspacehighway commented on packages/react-native/ReactCommon/react/renderer/components/view/conversions.h
> +              if (colorIt->second.hasValue()) {
here if JS color is `null` that only happens if user passed transition hint. Then the color in ColorStop gets default SharedColor value i.e. `HostPlatformColor::UndefinedColor`. So for black color it should be alright!

2025-01-03 08:45 UTC, intergalacticspacehighway commented on packages/react-native/React/Fabric/Utils/RCTLinearGradient.mm
> +      continue;
color in ColorStop is SharedColor instance which defaults to `HostPlatformColor::UndefinedColor` and it has [bool overload](https://github.com/facebook/react-native/blob/7e029b0dcf6d1a6455a8a6343457b70e353d0ff6/packages/react-native/ReactCommon/react/renderer/graphics/Color.h#L48) to check for undefined color. So i think black or such colors should be fine?

2025-01-03 08:46 UTC, intergalacticspacehighway commented on packages/react-native/Libraries/StyleSheet/__tests__/processBackgroundImage-test.js
> +  });
Agree, [added](https://github.com/facebook/react-native/pull/48410/commits/6913cdb54e02781ac357bcb64170331344ef1ebc).

2025-01-03 08:50 UTC, intergalacticspacehighway commented on packages/react-native/Libraries/StyleSheet/processBackgroundImage.js
> +    color: ColorStopColor,
Added a [comment](https://github.com/facebook/react-native/pull/48410/commits/6913cdb54e02781ac357bcb64170331344ef1ebc#diff-645b1d95fc4a2f92f0a8a2e695cd9b4c31ebc977adac0a38b39c46946f3fd530R25). Thanks!

2025-01-03 08:55 UTC, intergalacticspacehighway commented on packages/react-native/Libraries/StyleSheet/processBackgroundImage.js
> +            return [];
> Do transition hints have to be percentages?

They are actually `length-percentage` in the [spec](https://developer.mozilla.org/en-US/docs/Web/CSS/length-percentage). But i only added `%` support for now in color stops. Linear gradient support mixing `%` and `px` units which require us to know the dimension, for this we'll have to move color stop parsing to native side. I wanted to avoid that change until the new css parser. 

>  can you try to get rid of the top level if/else here and share some of this logic?

yeah i kinda prefer the explicit checks, also each branch has a tiny comment on top, but i will take another look!

2025-01-05 11:00 UTC, intergalacticspacehighway commented
@joevilches i added the `px` support as well and updated the PR description. sorry it increased the review surface and changes. But it was needed for web parity.

2025-01-06 19:11 UTC, joevilches approved these changes

2025-01-08 17:45 UTC, joevilches commented on packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/style/LinearGradient.kt
> +)
@intergalacticspacehighway got some internal comments mentioning we should use LengthPercentage here for `position`'s type: https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/LengthPercentage.kt

2025-01-09 02:25 UTC, intergalacticspacehighway commented on packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/style/LinearGradient.kt
> +)
Sure, [updated](https://github.com/facebook/react-native/pull/48410/commits/a1048a21ee728457e46f096fbec1a2bc5a9e88b7). I missed checking that out. Thanks!

2025-01-09 19:59 UTC, jorge-cab commented on packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/LengthPercentage.kt
> +    get() = _value
I think we can just change value to be public. We don't have to worry about the setter since its a val

2025-01-09 19:59 UTC, jorge-cab commented on packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/style/LinearGradient.kt
> +          colorStops.size - 1 -> newPosition = 1f
nit: 
```
newPosition = newPosition ?: when (i) {
    0 -> 0f
    colorStops.size - 1 -> 1f
}
```

2025-01-09 22:02 UTC, intergalacticspacehighway commented on packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/LengthPercentage.kt
> +    get() = _value
Cool. Updated. Thanks for reviewing.

2025-01-14 00:08 UTC, joevilches requested changes
A few more things with the new length percentage!

2025-01-14 00:08 UTC, joevilches commented on packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/style/LinearGradient.kt
> +      LengthPercentageType.PERCENT -> position.value / 100
are percents eval'ed relative to the gradientLineLength?

2025-01-14 06:40 UTC, intergalacticspacehighway commented on packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/LengthPercentage.kt
> +    public val value: Float,
Agree. [Updated](https://github.com/facebook/react-native/pull/48410/commits/5e31def8541048327a59e6bc65914c26768d748e). 

> are percents eval'ed relative to the gradientLineLength?

actually, `px` are relative to gradientLineLength 😅. android and iOS linear gradient APIs expect [0-1] value for color stop position. So we need [this](https://github.com/facebook/react-native/pull/48410/commits/5e31def8541048327a59e6bc65914c26768d748e#diff-39a947fba82999bc9e458030eb8395e411ea4a1564078e9af91174857f15e7edL388) kind of resolve . e.g. if user passes `50%` we just want to resolve it to `0.5` and If user passes `50px` then we need to resolve it relative to gradientLineLength `50 / gradientLineLength`

2025-01-14 06:40 UTC, intergalacticspacehighway commented on packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/style/LinearGradient.kt
> +      LengthPercentageType.PERCENT -> position.value / 100
actually, `px` are relative to gradientLineLength 😅. android and iOS linear gradient APIs expect [0-1] value for color stop position. So we need [this](https://github.com/facebook/react-native/pull/48410/commits/5e31def8541048327a59e6bc65914c26768d748e#diff-39a947fba82999bc9e458030eb8395e411ea4a1564078e9af91174857f15e7edL388) kind of resolve . e.g. if user passes `50%` we just want to resolve it to `0.5` and If user passes `50px` then we need to resolve it relative to gradientLineLength `50 / gradientLineLength`

2025-01-16 23:04 UTC, closed without merging